## Evaluate Presidio Analyzer using the Presidio Evaluator framework

This notebook demonstrates how to evaluate a Presidio instance using the presidio-evaluator framework
Steps:
1. Load dataset from file
2. Simple dataset statistics
3. Define the AnalyzerEngine object (and its parameters)
4. Align the dataset's entities to Presidio's entities
5. Set up the Evaluator object
6. Run experiment
7. Evaluate results
8. Error analysis

For an example with a custom Presidio instance, see [notebook 5](5_Evaluate_Custom_Presidio_Analyzer.ipynb).

In [21]:
# install presidio evaluator via pip if not yet installed

#!pip install presidio-evaluator

In [22]:
from pathlib import Path
from pprint import pprint
from collections import Counter
from typing import Dict, List
import json

from presidio_evaluator import InputSample
from presidio_evaluator.evaluation import SpanEvaluator, ModelError, Plotter
from presidio_evaluator.experiment_tracking import get_experiment_tracker

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

%reload_ext autoreload
%autoreload 2

## 1. Load dataset from file

In [23]:
dataset_name = "generated_size_1500_date_March_15_2026.json"
dataset = InputSample.read_dataset_json(Path(Path.cwd(), "data", dataset_name))
print(len(dataset))

tokenizing input: 100%|██████████| 1500/1500 [00:06<00:00, 229.04it/s]

1500

This dataset was auto generated. See more info here [Synthetic data generation](1_Generate_data.ipynb).

In [24]:
def get_entity_counts(dataset: List[InputSample]) -> Dict:
    """Return a dictionary with counter per entity type."""
    entity_counter = Counter()
    for sample in dataset:
        for tag in sample.tags:
            entity_counter[tag] += 1
    return entity_counter

In [25]:
def get_entity_counts(dataset: List[InputSample]) -> Dict:
    """Return a dictionary with counter per entity type."""
    entity_counter = Counter()
    for sample in dataset:
        print("SAMPLE:", sample)
        for tag in sample.tags:
            print("TAG:", tag)
            entity_counter[tag] += 1
    return entity_counter

entity_counts = get_entity_counts(dataset)
print(entity_counts)
pprint(entity_counts.most_common(), compact=True)

SAMPLE: Full text: My birthday is on the weekend. I'll turn 42.
Spans: [Span(type: AGE, value: 42, char_span: [41: 43])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
TAG: O
SAMPLE: Full text: Mrs. Kreutzmann flew to OSLO on Thursday morning.
Spans: [Span(type: DATE_TIME, value: Thursday, char_span: [32: 40]), Span(type: GPE, value: OSLO, char_span: [24: 28]), Span(type: PERSON, value: Kreutzmann, char_span: [5: 15]), Span(type: TITLE, value: Mrs., char_span: [0: 4])]

TAG: TITLE
TAG: PERSON
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
SAMPLE: Full text: Need to see last 10 transaction of card 4253978024025234633
Spans: [Span(type: CREDIT_CARD, value: 4253978024025234633, char_span: [40: 59])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
SAMPLE: Full text: You will be responsible for the husbandry and care of a large variety of species including lemurs, antelope, camels, and more
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: have you heard Mette Olsen speak yet?
Spans: [Span(type: PERSON, value: Mette Olsen, char_span: [15: 26])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: A tribute to Ava T. Hillary – sadly, she wasn't impressed.
Spans: [Span(type: PERSON, value: Ava T. Hillary, char_span: [13: 27])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Iceland was super fun to visit!
Spans: [Span(type: GPE, value: Iceland, char_span: [0: 7])]

TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: The title refers to Bedřicha Smetany 405 street in Kutná Hora 1. It was on this street that many of the clubs where Metallica first played were situated. "Battery is found in me" shows that these early shows on Stipo Way Street were important to them. Battery is where "lunacy finds you" and you "smash through the boundaries."
Spans: [Span(type: STREET_ADDRESS, value: Stipo Way, char_span: [211: 220]), Span(type: GPE, value: Kutná Hora 1, char_span: [51: 63]), Span(type: STREET_ADDRESS, value: Bedřicha Smetany 405, char_span: [20: 40])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I need to add my addresses, here they are: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, and 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay
Spans: [Span(type: STREET_ADDRESS, value: 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay, char_span: [86: 131]), Span(type: STREET_ADDRESS, value: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, char_span: [43: 80])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: Vanda Petheö will be talking in the conference
Spans: [Span(type: PERSON, value: Vanda Petheö, char_span: [0: 12])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: This 73 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 73, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: She was born on 7/8/1978. Her maiden name is Hofman
Spans: [Span(type: PERSON, value: Hofman, char_span: [45: 51]), Span(type: DATE_TIME, value: 7/8/1978, char_span: [16: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: I am thai but I live in Spain.
Spans: [Span(type: GPE, value: Spain, char_span: [24: 29]), Span(type: NRP, value: thai, char_span: [5: 9])]

TAG: O
TAG: O
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
SAMPLE: Full text: Zoolander is a 2010 Russian action-comedy film directed by Roland Aksyonov and starring Aksyonov
Spans: [Span(type: PERSON, value: Aksyonov, char_span: [88: 96]), Span(type: PERSON, value: Roland Aksyonov, char_span: [59: 74]), Span(type: NRP, value: Russian, char_span: [20: 27]), Span(type: DATE_TIME, value: 2010, char_span: [15: 19])]

TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: ??? Helga Reynisdóttir\n??? AK Steel Holding Corporation\n??? 489 Slovenčeva 107\n??? Suite 385\n??? Dutovlje\n??? Slovenia 08503
Spans: [Span(type: STREET_ADDRESS, value: 08503, char_span: [124: 129]), Span(type: GPE, value: Slovenia, char_span: [115: 123]), Span(type: GPE, value: Dutovlje, char_span: [101: 109]), Span(type: STREET_ADDRESS, value: Suite 385, char_span: [86: 95]), Span(type: STREET_ADDRESS, value: Slovenčeva 107, char_span: [66: 80]), Span(type: STREET_ADDRESS, value: 489, char_span: [62: 65]), Span(type: ORGANIZATION, value: AK Steel Holding Corporation, char_span: [28: 56]), Span(type: PERSON, value: Helga Reynisdóttir, char_span: [4: 22])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: STREET_ADDRESS
SAMPLE: Full text: What is procedure to redeem points won on credit card 3524303884637652 transactions ?
Spans: [Span(type: CREDIT_CARD, value: 3524303884637652, char_span: [54: 70])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
SAMPLE: Full text: God gave rock and roll to you, gave rock and roll to you, put it in the soul of everyone.
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: You said your email is DarijaBarisic@armyspy.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: DarijaBarisic@armyspy.com, char_span: [23: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My driver's license number is A3633861
Spans: [Span(type: US_DRIVER_LICENSE, value: A3633861, char_span: [30: 38])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: They're not answering at 9865 2117
Spans: [Span(type: PHONE_NUMBER, value: 9865 2117, char_span: [25: 34])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
SAMPLE: Full text: Ask the driver to stop at the corner of Schuepisstrasse 108 St. and Cunha Pass St.
Spans: [Span(type: STREET_ADDRESS, value: Cunha Pass, char_span: [68: 78]), Span(type: STREET_ADDRESS, value: Schuepisstrasse 108, char_span: [40: 59])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
SAMPLE: Full text: The bus drops you off at 0704 Rua das Hortências 1428 St.
Spans: [Span(type: STREET_ADDRESS, value: Rua das Hortências 1428, char_span: [30: 53]), Span(type: STREET_ADDRESS, value: 0704, char_span: [25: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
SAMPLE: Full text: We moved here from Spain
Spans: [Span(type: GPE, value: Spain, char_span: [19: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: I'm so jealous! said Tamara to Robert
Spans: [Span(type: PERSON, value: Robert, char_span: [31: 37]), Span(type: PERSON, value: Tamara, char_span: [21: 27])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
SAMPLE: Full text: The Polish Border Force have detained top-flight tennis player Tamara Trevisano over visa disputes.
Spans: [Span(type: PERSON, value: Tamara Trevisano, char_span: [63: 79]), Span(type: NRP, value: Polish, char_span: [4: 10])]

TAG: O
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name is Roland Pena but everyone calls me Roland
Spans: [Span(type: PERSON, value: roland, char_span: [45: 51]), Span(type: PERSON, value: roland pena, char_span: [11: 22])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: My driver's license number is 782459547569
Spans: [Span(type: US_DRIVER_LICENSE, value: 782459547569, char_span: [30: 42])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: Affiano Ferrari\n\nPodgorje pri Slovenj Gradcu\nSlovenia
Spans: [Span(type: GPE, value: Slovenia, char_span: [48: 56]), Span(type: GPE, value: Podgorje pri Slovenj Gradcu, char_span: [19: 46]), Span(type: PERSON, value: Affiano Ferrari, char_span: [0: 15])]

TAG: PERSON
TAG: PERSON
TAG: GPE
TAG: GPE
TAG: GPE
SAMPLE: Full text: We moved here from Estonia
Spans: [Span(type: GPE, value: Estonia, char_span: [19: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: How do I open my credit card statement?
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I want to add Viliam Brabec as a beneficiary to my account
Spans: [Span(type: PERSON, value: Viliam Brabec, char_span: [14: 27])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Please tell me your date of birth. It's 9/19/1957
Spans: [Span(type: DATE_TIME, value: 9/19/1957, char_span: [40: 49])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
SAMPLE: Full text: The Princess Royal arrived at Salumäe this morning from Estonia.
Spans: [Span(type: GPE, value: Estonia, char_span: [56: 63]), Span(type: GPE, value: Salumäe, char_span: [30: 37])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
SAMPLE: Full text: Ms. Barese flew to København K on Thursday morning.
Spans: [Span(type: DATE_TIME, value: Thursday, char_span: [34: 42]), Span(type: GPE, value: København K, char_span: [19: 30]), Span(type: PERSON, value: Barese, char_span: [4: 10]), Span(type: TITLE, value: Ms., char_span: [0: 3])]

TAG: TITLE
TAG: PERSON
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
SAMPLE: Full text: Have you been to a Harry C. Sheppard concert before?
Spans: [Span(type: PERSON, value: Harry C. Sheppard, char_span: [19: 36])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: It may be too that Tougas was influenced by an earlier song, "Carry Me Back To Denmark," which was arranged and sung by Vachel A Tougas in 2002 (though Davis's song was actually about a boat!).
Spans: [Span(type: PERSON, value: Davis, char_span: [152: 157]), Span(type: DATE_TIME, value: 2002, char_span: [139: 143]), Span(type: PERSON, value: Vachel A Tougas, char_span: [120: 135]), Span(type: GPE, value: Denmark, char_span: [79: 86]), Span(type: PERSON, value: Tougas, char_span: [19: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: card number 213113460645876 is lost, can you please send a new one to 16882 99 Balsham Road
 Suite 972
 HARROGATE
 United Kingdom? I am in COOLOOLA COVE for a business trip
Spans: [Span(type: GPE, value: COOLOOLA COVE, char_span: [139: 152]), Span(type: STREET_ADDRESS, value: 16882 99 Balsham Road
 Suite 972
 HARROGATE
 United Kingdom, char_span: [70: 129]), Span(type: CREDIT_CARD, value: 213113460645876, char_span: [12: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My brother just turned 65
Spans: [Span(type: AGE, value: 65, char_span: [23: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
SAMPLE: Full text: My zip code is 9100
Spans: [Span(type: ZIP_CODE, value: 9100, char_span: [15: 19])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: 68789 Nieuwkerk 67\n Apt. 508\n Goirle\n Netherlands 97672
Spans: [Span(type: STREET_ADDRESS, value: 97672, char_span: [53: 58]), Span(type: GPE, value: Netherlands, char_span: [41: 52]), Span(type: GPE, value: Goirle, char_span: [32: 38]), Span(type: STREET_ADDRESS, value: Apt. 508, char_span: [21: 29]), Span(type: STREET_ADDRESS, value: Nieuwkerk 67, char_span: [6: 18]), Span(type: STREET_ADDRESS, value: 68789, char_span: [0: 5])]

TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: GPE
TAG: GPE
TAG: STREET_ADDRESS
SAMPLE: Full text: You said your email is AntuValenciaCuellar@superrito.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: AntuValenciaCuellar@superrito.com, char_span: [23: 56])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: United Kingdom leader gives 'kill without warning' order
Spans: [Span(type: GPE, value: united kingdom, char_span: [0: 14])]

TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name is Burak
Spans: [Span(type: PERSON, value: Burak, char_span: [11: 16])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: We moved here from Cyprus (Greek)
Spans: [Span(type: GPE, value: Cyprus (Greek), char_span: [19: 33])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: GPE
TAG: GPE
SAMPLE: Full text: In Brazil they have company songs, musical expressions of employee loyalty sung by salarymen. Unfortunately, as regular RR commenter Victoria D Ershova points out, "most are horrible".
Spans: [Span(type: PERSON, value: Victoria D Ershova, char_span: [133: 151]), Span(type: GPE, value: Brazil, char_span: [3: 9])]

TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: During 1975, Vitec Group plc invested heavily in new microprocessor designs fostering the rapid growth of the computer industry.
Spans: [Span(type: ORGANIZATION, value: Vitec Group plc, char_span: [13: 28]), Span(type: DATE_TIME, value: 1975, char_span: [7: 11])]

TAG: O
TAG: DATE_TIME
TAG: O
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Just posted a photo http://www.shadowsgifts.com/
Spans: [Span(type: DOMAIN_NAME, value: http://www.shadowsgifts.com/, char_span: [20: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
SAMPLE: Full text: It's like that since 9/4/1977
Spans: [Span(type: DATE_TIME, value: 9/4/1977, char_span: [21: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
SAMPLE: Full text: Please transfer all funds from my account to this hackers' TintinForsberg@einrot.com
Spans: [Span(type: EMAIL_ADDRESS, value: TintinForsberg@einrot.com, char_span: [59: 84])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
SAMPLE: Full text: BlackRock Maryland Municipal Bond Trust\n\n755 Laan van Nieuw Oosteinde 142 Suite 076 Voorburg Netherlands
Spans: [Span(type: STREET_ADDRESS, value: 755 Laan van Nieuw Oosteinde 142 Suite 076 Voorburg Netherlands, char_span: [43: 106]), Span(type: ORGANIZATION, value: BlackRock Maryland Municipal Bond Trust, char_span: [0: 39])]

TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: Please charge my credit card. Number is 3519143550855668
Spans: [Span(type: CREDIT_CARD, value: 3519143550855668, char_span: [40: 56])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Mr. Raymond Hovestad?
Spans: [Span(type: PERSON, value: Raymond Hovestad, char_span: [88: 104]), Span(type: TITLE, value: Mr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: We moved here from Kapoly
Spans: [Span(type: GPE, value: Kapoly, char_span: [19: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: Martin: What a wife.\nCarolyn: Remember me, Robert? When I killed your brother, I talked just like this!\nKyle: You saved my life! How can I ever repay you?
Spans: [Span(type: PERSON, value: Kyle, char_span: [106: 110]), Span(type: PERSON, value: Robert, char_span: [44: 50]), Span(type: PERSON, value: Carolyn, char_span: [22: 29]), Span(type: PERSON, value: Martin, char_span: [0: 6])]

TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm moving out of the country, so please cancel my subscription
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: As promised, here's Arja's address:\n\n0128 C/ Manuel Iradier 41 Apt. 104 Adsubia Alicante
Spans: [Span(type: STREET_ADDRESS, value: 0128 C/ Manuel Iradier 41 Apt. 104 Adsubia Alicante, char_span: [39: 90]), Span(type: PERSON, value: Arja, char_span: [20: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: Please return to Rua Tomás Iriarte 950 Nikolaj Landing
 Apt. 427
 São Paulo
 Brazil 25310 in case of an issue.
Spans: [Span(type: STREET_ADDRESS, value: Rua Tomás Iriarte 950 Nikolaj Landing
 Apt. 427
 São Paulo
 Brazil 25310, char_span: [17: 89])]

TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O

## 2. Simple dataset statistics

In [26]:
entity_counts = get_entity_counts(dataset)
print("Count per entity:")
pprint(entity_counts.most_common(), compact=True)

print("\nMin and max number of tokens in dataset: "\
f"Min: {min([len(sample.tokens) for sample in dataset])}, "\
f"Max: {max([len(sample.tokens) for sample in dataset])}")

print(f"Min and max sentence length in dataset: " \
f"Min: {min([len(sample.full_text) for sample in dataset])}, "\
f"Max: {max([len(sample.full_text) for sample in dataset])}")

print("\nExample InputSample:")
print(dataset[0])

SAMPLE: Full text: My birthday is on the weekend. I'll turn 42.
Spans: [Span(type: AGE, value: 42, char_span: [41: 43])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
TAG: O
SAMPLE: Full text: Mrs. Kreutzmann flew to OSLO on Thursday morning.
Spans: [Span(type: DATE_TIME, value: Thursday, char_span: [32: 40]), Span(type: GPE, value: OSLO, char_span: [24: 28]), Span(type: PERSON, value: Kreutzmann, char_span: [5: 15]), Span(type: TITLE, value: Mrs., char_span: [0: 4])]

TAG: TITLE
TAG: PERSON
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
SAMPLE: Full text: Need to see last 10 transaction of card 4253978024025234633
Spans: [Span(type: CREDIT_CARD, value: 4253978024025234633, char_span: [40: 59])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
SAMPLE: Full text: You will be responsible for the husbandry and care of a large variety of species including lemurs, antelope, camels, and more
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: have you heard Mette Olsen speak yet?
Spans: [Span(type: PERSON, value: Mette Olsen, char_span: [15: 26])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: A tribute to Ava T. Hillary – sadly, she wasn't impressed.
Spans: [Span(type: PERSON, value: Ava T. Hillary, char_span: [13: 27])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Iceland was super fun to visit!
Spans: [Span(type: GPE, value: Iceland, char_span: [0: 7])]

TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: The title refers to Bedřicha Smetany 405 street in Kutná Hora 1. It was on this street that many of the clubs where Metallica first played were situated. "Battery is found in me" shows that these early shows on Stipo Way Street were important to them. Battery is where "lunacy finds you" and you "smash through the boundaries."
Spans: [Span(type: STREET_ADDRESS, value: Stipo Way, char_span: [211: 220]), Span(type: GPE, value: Kutná Hora 1, char_span: [51: 63]), Span(type: STREET_ADDRESS, value: Bedřicha Smetany 405, char_span: [20: 40])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I need to add my addresses, here they are: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, and 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay
Spans: [Span(type: STREET_ADDRESS, value: 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay, char_span: [86: 131]), Span(type: STREET_ADDRESS, value: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, char_span: [43: 80])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: Vanda Petheö will be talking in the conference
Spans: [Span(type: PERSON, value: Vanda Petheö, char_span: [0: 12])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: This 73 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 73, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: She was born on 7/8/1978. Her maiden name is Hofman
Spans: [Span(type: PERSON, value: Hofman, char_span: [45: 51]), Span(type: DATE_TIME, value: 7/8/1978, char_span: [16: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: I am thai but I live in Spain.
Spans: [Span(type: GPE, value: Spain, char_span: [24: 29]), Span(type: NRP, value: thai, char_span: [5: 9])]

TAG: O
TAG: O
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
SAMPLE: Full text: Zoolander is a 2010 Russian action-comedy film directed by Roland Aksyonov and starring Aksyonov
Spans: [Span(type: PERSON, value: Aksyonov, char_span: [88: 96]), Span(type: PERSON, value: Roland Aksyonov, char_span: [59: 74]), Span(type: NRP, value: Russian, char_span: [20: 27]), Span(type: DATE_TIME, value: 2010, char_span: [15: 19])]

TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: ??? Helga Reynisdóttir\n??? AK Steel Holding Corporation\n??? 489 Slovenčeva 107\n??? Suite 385\n??? Dutovlje\n??? Slovenia 08503
Spans: [Span(type: STREET_ADDRESS, value: 08503, char_span: [124: 129]), Span(type: GPE, value: Slovenia, char_span: [115: 123]), Span(type: GPE, value: Dutovlje, char_span: [101: 109]), Span(type: STREET_ADDRESS, value: Suite 385, char_span: [86: 95]), Span(type: STREET_ADDRESS, value: Slovenčeva 107, char_span: [66: 80]), Span(type: STREET_ADDRESS, value: 489, char_span: [62: 65]), Span(type: ORGANIZATION, value: AK Steel Holding Corporation, char_span: [28: 56]), Span(type: PERSON, value: Helga Reynisdóttir, char_span: [4: 22])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: STREET_ADDRESS
SAMPLE: Full text: What is procedure to redeem points won on credit card 3524303884637652 transactions ?
Spans: [Span(type: CREDIT_CARD, value: 3524303884637652, char_span: [54: 70])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
SAMPLE: Full text: God gave rock and roll to you, gave rock and roll to you, put it in the soul of everyone.
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: You said your email is DarijaBarisic@armyspy.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: DarijaBarisic@armyspy.com, char_span: [23: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My driver's license number is A3633861
Spans: [Span(type: US_DRIVER_LICENSE, value: A3633861, char_span: [30: 38])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: They're not answering at 9865 2117
Spans: [Span(type: PHONE_NUMBER, value: 9865 2117, char_span: [25: 34])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
SAMPLE: Full text: Ask the driver to stop at the corner of Schuepisstrasse 108 St. and Cunha Pass St.
Spans: [Span(type: STREET_ADDRESS, value: Cunha Pass, char_span: [68: 78]), Span(type: STREET_ADDRESS, value: Schuepisstrasse 108, char_span: [40: 59])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
SAMPLE: Full text: The bus drops you off at 0704 Rua das Hortências 1428 St.
Spans: [Span(type: STREET_ADDRESS, value: Rua das Hortências 1428, char_span: [30: 53]), Span(type: STREET_ADDRESS, value: 0704, char_span: [25: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
SAMPLE: Full text: We moved here from Spain
Spans: [Span(type: GPE, value: Spain, char_span: [19: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: I'm so jealous! said Tamara to Robert
Spans: [Span(type: PERSON, value: Robert, char_span: [31: 37]), Span(type: PERSON, value: Tamara, char_span: [21: 27])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
SAMPLE: Full text: The Polish Border Force have detained top-flight tennis player Tamara Trevisano over visa disputes.
Spans: [Span(type: PERSON, value: Tamara Trevisano, char_span: [63: 79]), Span(type: NRP, value: Polish, char_span: [4: 10])]

TAG: O
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name is Roland Pena but everyone calls me Roland
Spans: [Span(type: PERSON, value: roland, char_span: [45: 51]), Span(type: PERSON, value: roland pena, char_span: [11: 22])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: My driver's license number is 782459547569
Spans: [Span(type: US_DRIVER_LICENSE, value: 782459547569, char_span: [30: 42])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: Affiano Ferrari\n\nPodgorje pri Slovenj Gradcu\nSlovenia
Spans: [Span(type: GPE, value: Slovenia, char_span: [48: 56]), Span(type: GPE, value: Podgorje pri Slovenj Gradcu, char_span: [19: 46]), Span(type: PERSON, value: Affiano Ferrari, char_span: [0: 15])]

TAG: PERSON
TAG: PERSON
TAG: GPE
TAG: GPE
TAG: GPE
SAMPLE: Full text: We moved here from Estonia
Spans: [Span(type: GPE, value: Estonia, char_span: [19: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: How do I open my credit card statement?
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I want to add Viliam Brabec as a beneficiary to my account
Spans: [Span(type: PERSON, value: Viliam Brabec, char_span: [14: 27])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Please tell me your date of birth. It's 9/19/1957
Spans: [Span(type: DATE_TIME, value: 9/19/1957, char_span: [40: 49])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
SAMPLE: Full text: The Princess Royal arrived at Salumäe this morning from Estonia.
Spans: [Span(type: GPE, value: Estonia, char_span: [56: 63]), Span(type: GPE, value: Salumäe, char_span: [30: 37])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
SAMPLE: Full text: Ms. Barese flew to København K on Thursday morning.
Spans: [Span(type: DATE_TIME, value: Thursday, char_span: [34: 42]), Span(type: GPE, value: København K, char_span: [19: 30]), Span(type: PERSON, value: Barese, char_span: [4: 10]), Span(type: TITLE, value: Ms., char_span: [0: 3])]

TAG: TITLE
TAG: PERSON
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
SAMPLE: Full text: Have you been to a Harry C. Sheppard concert before?
Spans: [Span(type: PERSON, value: Harry C. Sheppard, char_span: [19: 36])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: It may be too that Tougas was influenced by an earlier song, "Carry Me Back To Denmark," which was arranged and sung by Vachel A Tougas in 2002 (though Davis's song was actually about a boat!).
Spans: [Span(type: PERSON, value: Davis, char_span: [152: 157]), Span(type: DATE_TIME, value: 2002, char_span: [139: 143]), Span(type: PERSON, value: Vachel A Tougas, char_span: [120: 135]), Span(type: GPE, value: Denmark, char_span: [79: 86]), Span(type: PERSON, value: Tougas, char_span: [19: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: card number 213113460645876 is lost, can you please send a new one to 16882 99 Balsham Road
 Suite 972
 HARROGATE
 United Kingdom? I am in COOLOOLA COVE for a business trip
Spans: [Span(type: GPE, value: COOLOOLA COVE, char_span: [139: 152]), Span(type: STREET_ADDRESS, value: 16882 99 Balsham Road
 Suite 972
 HARROGATE
 United Kingdom, char_span: [70: 129]), Span(type: CREDIT_CARD, value: 213113460645876, char_span: [12: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My brother just turned 65
Spans: [Span(type: AGE, value: 65, char_span: [23: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
SAMPLE: Full text: My zip code is 9100
Spans: [Span(type: ZIP_CODE, value: 9100, char_span: [15: 19])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: 68789 Nieuwkerk 67\n Apt. 508\n Goirle\n Netherlands 97672
Spans: [Span(type: STREET_ADDRESS, value: 97672, char_span: [53: 58]), Span(type: GPE, value: Netherlands, char_span: [41: 52]), Span(type: GPE, value: Goirle, char_span: [32: 38]), Span(type: STREET_ADDRESS, value: Apt. 508, char_span: [21: 29]), Span(type: STREET_ADDRESS, value: Nieuwkerk 67, char_span: [6: 18]), Span(type: STREET_ADDRESS, value: 68789, char_span: [0: 5])]

TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: GPE
TAG: GPE
TAG: STREET_ADDRESS
SAMPLE: Full text: You said your email is AntuValenciaCuellar@superrito.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: AntuValenciaCuellar@superrito.com, char_span: [23: 56])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: United Kingdom leader gives 'kill without warning' order
Spans: [Span(type: GPE, value: united kingdom, char_span: [0: 14])]

TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name is Burak
Spans: [Span(type: PERSON, value: Burak, char_span: [11: 16])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: We moved here from Cyprus (Greek)
Spans: [Span(type: GPE, value: Cyprus (Greek), char_span: [19: 33])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: GPE
TAG: GPE
SAMPLE: Full text: In Brazil they have company songs, musical expressions of employee loyalty sung by salarymen. Unfortunately, as regular RR commenter Victoria D Ershova points out, "most are horrible".
Spans: [Span(type: PERSON, value: Victoria D Ershova, char_span: [133: 151]), Span(type: GPE, value: Brazil, char_span: [3: 9])]

TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: During 1975, Vitec Group plc invested heavily in new microprocessor designs fostering the rapid growth of the computer industry.
Spans: [Span(type: ORGANIZATION, value: Vitec Group plc, char_span: [13: 28]), Span(type: DATE_TIME, value: 1975, char_span: [7: 11])]

TAG: O
TAG: DATE_TIME
TAG: O
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Just posted a photo http://www.shadowsgifts.com/
Spans: [Span(type: DOMAIN_NAME, value: http://www.shadowsgifts.com/, char_span: [20: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
SAMPLE: Full text: It's like that since 9/4/1977
Spans: [Span(type: DATE_TIME, value: 9/4/1977, char_span: [21: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
SAMPLE: Full text: Please transfer all funds from my account to this hackers' TintinForsberg@einrot.com
Spans: [Span(type: EMAIL_ADDRESS, value: TintinForsberg@einrot.com, char_span: [59: 84])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
SAMPLE: Full text: BlackRock Maryland Municipal Bond Trust\n\n755 Laan van Nieuw Oosteinde 142 Suite 076 Voorburg Netherlands
Spans: [Span(type: STREET_ADDRESS, value: 755 Laan van Nieuw Oosteinde 142 Suite 076 Voorburg Netherlands, char_span: [43: 106]), Span(type: ORGANIZATION, value: BlackRock Maryland Municipal Bond Trust, char_span: [0: 39])]

TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: Please charge my credit card. Number is 3519143550855668
Spans: [Span(type: CREDIT_CARD, value: 3519143550855668, char_span: [40: 56])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Mr. Raymond Hovestad?
Spans: [Span(type: PERSON, value: Raymond Hovestad, char_span: [88: 104]), Span(type: TITLE, value: Mr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: We moved here from Kapoly
Spans: [Span(type: GPE, value: Kapoly, char_span: [19: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: Martin: What a wife.\nCarolyn: Remember me, Robert? When I killed your brother, I talked just like this!\nKyle: You saved my life! How can I ever repay you?
Spans: [Span(type: PERSON, value: Kyle, char_span: [106: 110]), Span(type: PERSON, value: Robert, char_span: [44: 50]), Span(type: PERSON, value: Carolyn, char_span: [22: 29]), Span(type: PERSON, value: Martin, char_span: [0: 6])]

TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm moving out of the country, so please cancel my subscription
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: As promised, here's Arja's address:\n\n0128 C/ Manuel Iradier 41 Apt. 104 Adsubia Alicante
Spans: [Span(type: STREET_ADDRESS, value: 0128 C/ Manuel Iradier 41 Apt. 104 Adsubia Alicante, char_span: [39: 90]), Span(type: PERSON, value: Arja, char_span: [20: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: Please return to Rua Tomás Iriarte 950 Nikolaj Landing
 Apt. 427
 São Paulo
 Brazil 25310 in case of an issue.
Spans: [Span(type: STREET_ADDRESS, value: Rua Tomás Iriarte 950 Nikolaj Landing
 Apt. 427
 São Paulo
 Brazil 25310, char_span: [17: 89])]

TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O

In [27]:
print("A few examples sentences containing each entity:\n")
for entity in entity_counts.keys():
    samples = [sample for sample in dataset if entity in set(sample.tags)]
    if len(samples) > 1 and entity != "O":
        print(f"Entity: <{entity}> two example sentences:\n"
              f"\n1) {samples[0].full_text}"
              f"\n2) {samples[1].full_text}"
              f"\n------------------------------------\n")

A few examples sentences containing each entity:

Entity: <AGE> two example sentences:

1) My birthday is on the weekend. I'll turn 42.
2) This 73 year old female complaining of stomach pain.
------------------------------------

Entity: <TITLE> two example sentences:

1) Mrs. Kreutzmann flew to OSLO on Thursday morning.
2) Ms. Barese flew to København K on Thursday morning.
------------------------------------

Entity: <PERSON> two example sentences:

1) Mrs. Kreutzmann flew to OSLO on Thursday morning.
2) have you heard Mette Olsen speak yet?
------------------------------------

Entity: <GPE> two example sentences:

1) Mrs. Kreutzmann flew to OSLO on Thursday morning.
2) Iceland was super fun to visit!
------------------------------------

Entity: <DATE_TIME> two example sentences:

1) Mrs. Kreutzmann flew to OSLO on Thursday morning.
2) She was born on 7/8/1978. Her maiden name is Hofman
------------------------------------

Entity: <CREDIT_CARD> two example sentences:

1) Need to see last 10 transaction of card 4253978024025234633
2) What is procedure to redeem points won on credit card 3524303884637652 transactions ?
------------------------------------

Entity: <STREET_ADDRESS> two example sentences:

1) The title refers to Bedřicha Smetany 405 street in Kutná Hora 1. It was on this street that many of the clubs where Metallica first played were situated. "Battery is found in me" shows that these early shows on Stipo Way Street were important to them. Battery is where "lunacy finds you" and you "smash through the boundaries."
2) I need to add my addresses, here they are: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, and 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay
------------------------------------

Entity: <NRP> two example sentences:

1) I am thai but I live in Spain.
2) Zoolander is a 2010 Russian action-comedy film directed by Roland Aksyonov and starring Aksyonov
------------------------------------

Entity: <ORGANIZATION> two example sentences:

1) ??? Helga Reynisdóttir\n??? AK Steel Holding Corporation\n??? 489 Slovenčeva 107\n??? Suite 385\n??? Dutovlje\n??? Slovenia 08503
2) During 1975, Vitec Group plc invested heavily in new microprocessor designs fostering the rapid growth of the computer industry.
------------------------------------

Entity: <EMAIL_ADDRESS> two example sentences:

1) You said your email is DarijaBarisic@armyspy.com. Is that correct?
2) You said your email is AntuValenciaCuellar@superrito.com. Is that correct?
------------------------------------

Entity: <US_DRIVER_LICENSE> two example sentences:

1) My driver's license number is A3633861
2) My driver's license number is 782459547569
------------------------------------

Entity: <PHONE_NUMBER> two example sentences:

1) They're not answering at 9865 2117
2) Nestor Afanasyev\nShoal Point Energy Ltd.\n476 Riedbergstrasse 50
 Apt. 134
 ZWISL
 Austria\n(81) 9162-5824 office\n+41 25 787 11 72 fax\n+41 43 115 43 32 mobile\n
------------------------------------

Entity: <ZIP_CODE> two example sentences:

1) My zip code is 9100
2) My zip code is 8405
------------------------------------

Entity: <DOMAIN_NAME> two example sentences:

1) Just posted a photo http://www.shadowsgifts.com/
2) My website is https://www.BowlingGrip.is/
------------------------------------

Entity: <US_SSN> two example sentences:

1) His social security number is 772-49-0268
2) His social security number is 509-83-1134
------------------------------------

Entity: <IBAN_CODE> two example sentences:

1) My IBAN is GB28WUOQ27073855220238
2) Hi Rikke, I'm contacting you about a problem I have with sending a wire transfer using this IBAN GB95WPQU04526617296772
------------------------------------

Entity: <IP_ADDRESS> two example sentences:

1) I can't browse to your site, keep getting address 57.140.2.49 blocked error
2) Inject SELECT * FROM Users WHERE client_ip = ?%//!%20\|220.21.5.178|%20/
------------------------------------

## 3. Define the AnalyzerEngine object 
Using Presidio with default parameters (not recommended, it's used here for simplicity). For an example on customization, see [notebook 5](5_Evaluate_Custom_Presidio_Analyzer.ipynb)

In [28]:
from presidio_analyzer import AnalyzerEngine
from presidio_analyzer.nlp_engine import NlpEngineProvider

# Loading the vanilla Analyzer Engine, with the default NER model.
configuration = {
    "nlp_engine_name": "spacy",
    "models": [{"lang_code": "en", "model_name": "en_core_web_sm"}],
}
provider = NlpEngineProvider(nlp_configuration=configuration)
nlp_engine_with_sm = provider.create_engine()
analyzer_engine = AnalyzerEngine(nlp_engine=nlp_engine_with_sm, default_score_threshold=0.4)

pprint(f"Supported entities for English:")
pprint(analyzer_engine.get_supported_entities("en"), compact=True)

print(f"\nLoaded recognizers for English:")
pprint([rec.name for rec in analyzer_engine.registry.get_recognizers("en", all_fields=True)], compact=True)

print(f"\nLoaded NER models:")
pprint(analyzer_engine.nlp_engine.models)

'Supported entities for English:'
['US_SSN', 'EMAIL', 'URL', 'US_DRIVER_LICENSE', 'AGE', 'US_PASSPORT', 'PERSON',
 'ID', 'MAC_ADDRESS', 'IP_ADDRESS', 'MEDICAL_LICENSE', 'CREDIT_CARD',
 'IBAN_CODE', 'LOCATION', 'DATE_TIME', 'PHONE_NUMBER', 'NRP', 'US_BANK_NUMBER',
 'UK_NHS', 'ORGANIZATION', 'CRYPTO', 'US_ITIN', 'EMAIL_ADDRESS']

Loaded recognizers for English:
['CreditCardRecognizer', 'UsBankRecognizer', 'UsLicenseRecognizer',
 'UsItinRecognizer', 'UsPassportRecognizer', 'UsSsnRecognizer', 'NhsRecognizer',
 'CryptoRecognizer', 'DateRecognizer', 'EmailRecognizer', 'IbanRecognizer',
 'IpRecognizer', 'MedicalLicenseRecognizer', 'MacAddressRecognizer',
 'PhoneRecognizer', 'UrlRecognizer', 'SpacyRecognizer']

Loaded NER models:
[{'lang_code': 'en', 'model_name': 'en_core_web_sm'}]

## 4. Align the dataset's entities to Presidio's entities

There is possibly a difference between the names of entities in the dataset, and the names of entities Presidio can detect.
For example, it could be that a dataset labels a name as PER while Presidio returns PERSON. To be able to compare the predicted value to the actual and gather metrics, an alignment between the entity names is necessary. Consider changing the mapping if your dataset and/or Presidio instance supports difference entity types.

In [29]:
from presidio_evaluator.models import  PresidioAnalyzerWrapper

entities_mapping=PresidioAnalyzerWrapper.presidio_entities_map # default mapping

print("Using this mapping between the dataset and Presidio's entities:")
pprint(entities_mapping, compact=True)


dataset = SpanEvaluator.align_entity_types(
    dataset, 
    entities_mapping=entities_mapping, 
    allow_missing_mappings=True
)
new_entity_counts = get_entity_counts(dataset)
print("\nCount per entity after alignment:")
pprint(new_entity_counts.most_common(), compact=True)

dataset_entities = list(new_entity_counts.values())

Using this mapping between the dataset and Presidio's entities:
{'ADDRESS': 'LOCATION',
 'AGE': 'AGE',
 'BIRTHDAY': 'DATE_TIME',
 'CITY': 'LOCATION',
 'CREDIT_CARD': 'CREDIT_CARD',
 'CREDIT_CARD_NUMBER': 'CREDIT_CARD',
 'DATE': 'DATE_TIME',
 'DATE_OF_BIRTH': 'DATE_TIME',
 'DATE_TIME': 'DATE_TIME',
 'DOB': 'DATE_TIME',
 'DOMAIN': 'URL',
 'DOMAIN_NAME': 'URL',
 'EMAIL': 'EMAIL_ADDRESS',
 'EMAIL_ADDRESS': 'EMAIL_ADDRESS',
 'FACILITY': 'LOCATION',
 'FIRST_NAME': 'PERSON',
 'GPE': 'LOCATION',
 'HCW': 'PERSON',
 'HOSP': 'ORGANIZATION',
 'HOSPITAL': 'ORGANIZATION',
 'IBAN': 'IBAN_CODE',
 'IBAN_CODE': 'IBAN_CODE',
 'ID': 'ID',
 'IP_ADDRESS': 'IP_ADDRESS',
 'LAST_NAME': 'PERSON',
 'LOC': 'LOCATION',
 'LOCATION': 'LOCATION',
 'NAME': 'PERSON',
 'NATIONALITY': 'NRP',
 'NORP': 'NRP',
 'NRP': 'NRP',
 'O': 'O',
 'ORG': 'ORGANIZATION',
 'ORGANIZATION': 'ORGANIZATION',
 'PATIENT': 'PERSON',
 'PATORG': 'ORGANIZATION',
 'PER': 'PERSON',
 'PERSON': 'PERSON',
 'PHONE': 'PHONE_NUMBER',
 'PHONE_NUMBER': 'PHONE_NUMBER',
 'PREFIX': 'TITLE',
 'SSN': 'US_SSN',
 'STAFF': 'PERSON',
 'STREET_ADDRESS': 'LOCATION',
 'TIME': 'DATE_TIME',
 'TITLE': 'TITLE',
 'URL': 'URL',
 'US_DRIVER_LICENSE': 'US_DRIVER_LICENSE',
 'US_SSN': 'US_SSN',
 'VENDOR': 'ORGANIZATION',
 'ZIP': 'ZIP_CODE',
 'ZIP_CODE': 'ZIP_CODE'}
SAMPLE: Full text: My birthday is on the weekend. I'll turn 42.
Spans: [Span(type: AGE, value: 42, char_span: [41: 43])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
TAG: O
SAMPLE: Full text: Mrs. Kreutzmann flew to OSLO on Thursday morning.
Spans: [Span(type: DATE_TIME, value: Thursday, char_span: [32: 40]), Span(type: LOCATION, value: OSLO, char_span: [24: 28]), Span(type: PERSON, value: Kreutzmann, char_span: [5: 15]), Span(type: TITLE, value: Mrs., char_span: [0: 4])]

TAG: TITLE
TAG: PERSON
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
SAMPLE: Full text: Need to see last 10 transaction of card 4253978024025234633
Spans: [Span(type: CREDIT_CARD, value: 4253978024025234633, char_span: [40: 59])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
SAMPLE: Full text: You will be responsible for the husbandry and care of a large variety of species including lemurs, antelope, camels, and more
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: have you heard Mette Olsen speak yet?
Spans: [Span(type: PERSON, value: Mette Olsen, char_span: [15: 26])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: A tribute to Ava T. Hillary – sadly, she wasn't impressed.
Spans: [Span(type: PERSON, value: Ava T. Hillary, char_span: [13: 27])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Iceland was super fun to visit!
Spans: [Span(type: LOCATION, value: Iceland, char_span: [0: 7])]

TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: The title refers to Bedřicha Smetany 405 street in Kutná Hora 1. It was on this street that many of the clubs where Metallica first played were situated. "Battery is found in me" shows that these early shows on Stipo Way Street were important to them. Battery is where "lunacy finds you" and you "smash through the boundaries."
Spans: [Span(type: LOCATION, value: Stipo Way, char_span: [211: 220]), Span(type: LOCATION, value: Kutná Hora 1, char_span: [51: 63]), Span(type: LOCATION, value: Bedřicha Smetany 405, char_span: [20: 40])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I need to add my addresses, here they are: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, and 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay
Spans: [Span(type: LOCATION, value: 72513 Ibirapita 8057 Apt. 286 Dolores Uruguay, char_span: [86: 131]), Span(type: LOCATION, value: 314 Αρτεμισίου 62 Apt. 601 ΛΕΜΕΣΟΣ LI, char_span: [43: 80])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: Vanda Petheö will be talking in the conference
Spans: [Span(type: PERSON, value: Vanda Petheö, char_span: [0: 12])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: This 73 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 73, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: She was born on 7/8/1978. Her maiden name is Hofman
Spans: [Span(type: PERSON, value: Hofman, char_span: [45: 51]), Span(type: DATE_TIME, value: 7/8/1978, char_span: [16: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: I am thai but I live in Spain.
Spans: [Span(type: LOCATION, value: Spain, char_span: [24: 29]), Span(type: NRP, value: thai, char_span: [5: 9])]

TAG: O
TAG: O
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
SAMPLE: Full text: Zoolander is a 2010 Russian action-comedy film directed by Roland Aksyonov and starring Aksyonov
Spans: [Span(type: PERSON, value: Aksyonov, char_span: [88: 96]), Span(type: PERSON, value: Roland Aksyonov, char_span: [59: 74]), Span(type: NRP, value: Russian, char_span: [20: 27]), Span(type: DATE_TIME, value: 2010, char_span: [15: 19])]

TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: ??? Helga Reynisdóttir\n??? AK Steel Holding Corporation\n??? 489 Slovenčeva 107\n??? Suite 385\n??? Dutovlje\n??? Slovenia 08503
Spans: [Span(type: LOCATION, value: 08503, char_span: [124: 129]), Span(type: LOCATION, value: Slovenia, char_span: [115: 123]), Span(type: LOCATION, value: Dutovlje, char_span: [101: 109]), Span(type: LOCATION, value: Suite 385, char_span: [86: 95]), Span(type: LOCATION, value: Slovenčeva 107, char_span: [66: 80]), Span(type: LOCATION, value: 489, char_span: [62: 65]), Span(type: ORGANIZATION, value: AK Steel Holding Corporation, char_span: [28: 56]), Span(type: PERSON, value: Helga Reynisdóttir, char_span: [4: 22])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: What is procedure to redeem points won on credit card 3524303884637652 transactions ?
Spans: [Span(type: CREDIT_CARD, value: 3524303884637652, char_span: [54: 70])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
SAMPLE: Full text: God gave rock and roll to you, gave rock and roll to you, put it in the soul of everyone.
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: You said your email is DarijaBarisic@armyspy.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: DarijaBarisic@armyspy.com, char_span: [23: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My driver's license number is A3633861
Spans: [Span(type: US_DRIVER_LICENSE, value: A3633861, char_span: [30: 38])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: They're not answering at 9865 2117
Spans: [Span(type: PHONE_NUMBER, value: 9865 2117, char_span: [25: 34])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
SAMPLE: Full text: Ask the driver to stop at the corner of Schuepisstrasse 108 St. and Cunha Pass St.
Spans: [Span(type: LOCATION, value: Cunha Pass, char_span: [68: 78]), Span(type: LOCATION, value: Schuepisstrasse 108, char_span: [40: 59])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
SAMPLE: Full text: The bus drops you off at 0704 Rua das Hortências 1428 St.
Spans: [Span(type: LOCATION, value: Rua das Hortências 1428, char_span: [30: 53]), Span(type: LOCATION, value: 0704, char_span: [25: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
SAMPLE: Full text: We moved here from Spain
Spans: [Span(type: LOCATION, value: Spain, char_span: [19: 24])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
SAMPLE: Full text: I'm so jealous! said Tamara to Robert
Spans: [Span(type: PERSON, value: Robert, char_span: [31: 37]), Span(type: PERSON, value: Tamara, char_span: [21: 27])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
SAMPLE: Full text: The Polish Border Force have detained top-flight tennis player Tamara Trevisano over visa disputes.
Spans: [Span(type: PERSON, value: Tamara Trevisano, char_span: [63: 79]), Span(type: NRP, value: Polish, char_span: [4: 10])]

TAG: O
TAG: NRP
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name is Roland Pena but everyone calls me Roland
Spans: [Span(type: PERSON, value: roland, char_span: [45: 51]), Span(type: PERSON, value: roland pena, char_span: [11: 22])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: My driver's license number is 782459547569
Spans: [Span(type: US_DRIVER_LICENSE, value: 782459547569, char_span: [30: 42])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: Affiano Ferrari\n\nPodgorje pri Slovenj Gradcu\nSlovenia
Spans: [Span(type: LOCATION, value: Slovenia, char_span: [48: 56]), Span(type: LOCATION, value: Podgorje pri Slovenj Gradcu, char_span: [19: 46]), Span(type: PERSON, value: Affiano Ferrari, char_span: [0: 15])]

TAG: PERSON
TAG: PERSON
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: We moved here from Estonia
Spans: [Span(type: LOCATION, value: Estonia, char_span: [19: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
SAMPLE: Full text: How do I open my credit card statement?
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I want to add Viliam Brabec as a beneficiary to my account
Spans: [Span(type: PERSON, value: Viliam Brabec, char_span: [14: 27])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Please tell me your date of birth. It's 9/19/1957
Spans: [Span(type: DATE_TIME, value: 9/19/1957, char_span: [40: 49])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
SAMPLE: Full text: The Princess Royal arrived at Salumäe this morning from Estonia.
Spans: [Span(type: LOCATION, value: Estonia, char_span: [56: 63]), Span(type: LOCATION, value: Salumäe, char_span: [30: 37])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
SAMPLE: Full text: Ms. Barese flew to København K on Thursday morning.
Spans: [Span(type: DATE_TIME, value: Thursday, char_span: [34: 42]), Span(type: LOCATION, value: København K, char_span: [19: 30]), Span(type: PERSON, value: Barese, char_span: [4: 10]), Span(type: TITLE, value: Ms., char_span: [0: 3])]

TAG: TITLE
TAG: PERSON
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
SAMPLE: Full text: Have you been to a Harry C. Sheppard concert before?
Spans: [Span(type: PERSON, value: Harry C. Sheppard, char_span: [19: 36])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: It may be too that Tougas was influenced by an earlier song, "Carry Me Back To Denmark," which was arranged and sung by Vachel A Tougas in 2002 (though Davis's song was actually about a boat!).
Spans: [Span(type: PERSON, value: Davis, char_span: [152: 157]), Span(type: DATE_TIME, value: 2002, char_span: [139: 143]), Span(type: PERSON, value: Vachel A Tougas, char_span: [120: 135]), Span(type: LOCATION, value: Denmark, char_span: [79: 86]), Span(type: PERSON, value: Tougas, char_span: [19: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: card number 213113460645876 is lost, can you please send a new one to 16882 99 Balsham Road
 Suite 972
 HARROGATE
 United Kingdom? I am in COOLOOLA COVE for a business trip
Spans: [Span(type: LOCATION, value: COOLOOLA COVE, char_span: [139: 152]), Span(type: LOCATION, value: 16882 99 Balsham Road
 Suite 972
 HARROGATE
 United Kingdom, char_span: [70: 129]), Span(type: CREDIT_CARD, value: 213113460645876, char_span: [12: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My brother just turned 65
Spans: [Span(type: AGE, value: 65, char_span: [23: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
SAMPLE: Full text: My zip code is 9100
Spans: [Span(type: ZIP_CODE, value: 9100, char_span: [15: 19])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: 68789 Nieuwkerk 67\n Apt. 508\n Goirle\n Netherlands 97672
Spans: [Span(type: LOCATION, value: 97672, char_span: [53: 58]), Span(type: LOCATION, value: Netherlands, char_span: [41: 52]), Span(type: LOCATION, value: Goirle, char_span: [32: 38]), Span(type: LOCATION, value: Apt. 508, char_span: [21: 29]), Span(type: LOCATION, value: Nieuwkerk 67, char_span: [6: 18]), Span(type: LOCATION, value: 68789, char_span: [0: 5])]

TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: You said your email is AntuValenciaCuellar@superrito.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: AntuValenciaCuellar@superrito.com, char_span: [23: 56])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: United Kingdom leader gives 'kill without warning' order
Spans: [Span(type: LOCATION, value: united kingdom, char_span: [0: 14])]

TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name is Burak
Spans: [Span(type: PERSON, value: Burak, char_span: [11: 16])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: We moved here from Cyprus (Greek)
Spans: [Span(type: LOCATION, value: Cyprus (Greek), char_span: [19: 33])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: In Brazil they have company songs, musical expressions of employee loyalty sung by salarymen. Unfortunately, as regular RR commenter Victoria D Ershova points out, "most are horrible".
Spans: [Span(type: PERSON, value: Victoria D Ershova, char_span: [133: 151]), Span(type: LOCATION, value: Brazil, char_span: [3: 9])]

TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: During 1975, Vitec Group plc invested heavily in new microprocessor designs fostering the rapid growth of the computer industry.
Spans: [Span(type: ORGANIZATION, value: Vitec Group plc, char_span: [13: 28]), Span(type: DATE_TIME, value: 1975, char_span: [7: 11])]

TAG: O
TAG: DATE_TIME
TAG: O
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Just posted a photo http://www.shadowsgifts.com/
Spans: [Span(type: URL, value: http://www.shadowsgifts.com/, char_span: [20: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: URL
SAMPLE: Full text: It's like that since 9/4/1977
Spans: [Span(type: DATE_TIME, value: 9/4/1977, char_span: [21: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
SAMPLE: Full text: Please transfer all funds from my account to this hackers' TintinForsberg@einrot.com
Spans: [Span(type: EMAIL_ADDRESS, value: TintinForsberg@einrot.com, char_span: [59: 84])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
SAMPLE: Full text: BlackRock Maryland Municipal Bond Trust\n\n755 Laan van Nieuw Oosteinde 142 Suite 076 Voorburg Netherlands
Spans: [Span(type: LOCATION, value: 755 Laan van Nieuw Oosteinde 142 Suite 076 Voorburg Netherlands, char_span: [43: 106]), Span(type: ORGANIZATION, value: BlackRock Maryland Municipal Bond Trust, char_span: [0: 39])]

TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: Please charge my credit card. Number is 3519143550855668
Spans: [Span(type: CREDIT_CARD, value: 3519143550855668, char_span: [40: 56])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Mr. Raymond Hovestad?
Spans: [Span(type: PERSON, value: Raymond Hovestad, char_span: [88: 104]), Span(type: TITLE, value: Mr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: We moved here from Kapoly
Spans: [Span(type: LOCATION, value: Kapoly, char_span: [19: 25])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
SAMPLE: Full text: Martin: What a wife.\nCarolyn: Remember me, Robert? When I killed your brother, I talked just like this!\nKyle: You saved my life! How can I ever repay you?
Spans: [Span(type: PERSON, value: Kyle, char_span: [106: 110]), Span(type: PERSON, value: Robert, char_span: [44: 50]), Span(type: PERSON, value: Carolyn, char_span: [22: 29]), Span(type: PERSON, value: Martin, char_span: [0: 6])]

TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm moving out of the country, so please cancel my subscription
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: As promised, here's Arja's address:\n\n0128 C/ Manuel Iradier 41 Apt. 104 Adsubia Alicante

## 5. Set up the Evaluator object

In [30]:
# Set up the experiment tracker to log the experiment for reproducibility
experiment = get_experiment_tracker()

# Create the evaluator object
evaluator = SpanEvaluator(model=analyzer_engine)


# Track model and dataset params
params = {"dataset_name": dataset_name, 
          "model_name": evaluator.model.name}
params.update(evaluator.model.to_log())
experiment.log_parameters(params)
experiment.log_dataset_hash(dataset)
experiment.log_parameter("entity_mappings", json.dumps(entities_mapping))

--------
Entities supported by this Presidio Analyzer instance:
US_SSN, EMAIL, URL, US_DRIVER_LICENSE, AGE, US_PASSPORT, PERSON, ID, MAC_ADDRESS, IP_ADDRESS, MEDICAL_LICENSE, CREDIT_CARD, IBAN_CODE, LOCATION, DATE_TIME, PHONE_NUMBER, NRP, US_BANK_NUMBER, UK_NHS, ORGANIZATION, CRYPTO, US_ITIN, EMAIL_ADDRESS

/Users/jyu36/code/ic-llm/presidio/.venv/lib/python3.12/site-packages/presidio_evaluator/evaluation/base_evaluator.py:83: UserWarning: skip words not provided, using default skip words. If you want the evaluation to not use skip words, pass skip_words=[]
  warnings.warn("skip words not provided, using default skip words. "

## 6. Run experiment

In [31]:
%%time

## Run experiment

evaluation_results = evaluator.evaluate_all(dataset)
results = evaluator.calculate_score(evaluation_results)

# Track experiment results
experiment.log_metrics(results.to_log())
entities, confmatrix = results.to_confusion_matrix()
experiment.log_confusion_matrix(matrix=confmatrix, 
                                labels=entities)

# end experiment
experiment.end()

Running model PresidioAnalyzerWrapper on dataset...
Finished running model on dataset
saving experiment data to /Users/jyu36/code/ic-llm/presidio/experiment_20260316-194056.json
CPU times: user 9.61 s, sys: 147 ms, total: 9.76 s
Wall time: 10 s

## 7. Evaluate results

In [32]:
# Plot output
plotter = Plotter(results=results, 
                  model_name = evaluator.model.name, 
                  save_as="svg",
                  beta = 2) 

# Path of the directory to save the plots
output_folder = Path(Path.cwd(), "plotter_output")
plotter.plot_scores(output_folder=output_folder)

In [33]:
pprint({"PII F":results.pii_f, "PII recall": results.pii_recall, "PII precision": results.pii_precision})

{'PII F': 0.6608153198897433,
 'PII precision': 0.6938309215536939,
 'PII recall': 0.6530465949820788}

### 7a. False positives
#### Most common false positive tokens:

In [34]:
ModelError.most_common_fp_tokens(results.model_errors)

Most common false positive tokens:
[('devil', 18),
 ('iban', 15),
 ('co.ltd', 13),
 ('10th', 10),
 ('pedestrians', 10),
 ('comedy kids family mystery suspense\\ndirected', 9),
 ('zoolander', 8),
 ('hobbits', 8),
 ('fuse tv', 7),
 ('70', 7)]
---------------
Example sentence with each FP token:
	- Devil (`devil` pred as ORGANIZATION)
	- IBAN (`iban` pred as ORGANIZATION)
	- CO.LTD (`co.ltd` pred as O)
	- 10th year (`10th` pred as DATE_TIME)
	- Pedestrians (`pedestrians` pred as NRP)
	- Comedy , Kids & Family Mystery & Suspense\nDirected (`comedy kids family mystery suspense\ndirected` pred as ORGANIZATION)
	- Zoolander (`zoolander` pred as ORGANIZATION)
	- Hobbits (`hobbits` pred as ORGANIZATION)
	- Fuse TV (`fuse tv` pred as ORGANIZATION)
	- 70 year old (`70` pred as O)

[('devil', 18),
 ('iban', 15),
 ('co.ltd', 13),
 ('10th', 10),
 ('pedestrians', 10),
 ('comedy kids family mystery suspense\\ndirected', 9),
 ('zoolander', 8),
 ('hobbits', 8),
 ('fuse tv', 7),
 ('70', 7)]

#### More FP analysis

In [35]:
fps_df = ModelError.get_fps_dataframe(results.model_errors, entity=["PERSON"])
fps_df[["full_text", "token", "annotation", "prediction"]].head(20)

                  full_text                   token    annotation prediction
0                Discipline              discipline             O     PERSON
1               Salesperson             salesperson             O     PERSON
2                 Orchestra               orchestra             O     PERSON
3               Salesperson             salesperson             O     PERSON
4                Discipline              discipline             O     PERSON
5                 Orchestra               orchestra             O     PERSON
6                Discipline              discipline             O     PERSON
7                Discipline              discipline             O     PERSON
8               Salesperson             salesperson             O     PERSON
9                Discipline              discipline             O     PERSON
10              Salesperson             salesperson             O     PERSON
11                Orchestra               orchestra             O     PERSON
12                   Hofman                  hofman  ORGANIZATION     PERSON
13                   Tougas                  tougas      LOCATION     PERSON
14          Vachel A Tougas           vachel tougas  ORGANIZATION     PERSON
15                    Burak                   burak  ORGANIZATION     PERSON
16                     Arja                    arja  ORGANIZATION     PERSON
17               Uwe Sommer              uwe sommer  ORGANIZATION     PERSON
18   Myron Sergeyev\n\n4939  myron sergeyev\n\n4939  ORGANIZATION     PERSON
19  Paien de Launay\nWeight    paien launay\nweight  ORGANIZATION     PERSON

### 7b. False negatives (FN)

#### Most common false negative examples + a few samples with FN

In [36]:
ModelError.most_common_fn_tokens(results.model_errors, n=15)

Most common false negative tokens:
[('ms.', 10),
 ('dr.', 8),
 ('38', 7),
 ('19', 7),
 ('73', 6),
 ('70', 6),
 ('cyprus greek', 5),
 ('53', 5),
 ('greenlander', 5),
 ('55', 4),
 ('77', 4),
 ('43', 4),
 ('72', 4),
 ('62', 4),
 ('76', 4)]
---------------
Example sentence with each FN token:
	- Ms. (`ms.` annotated as O)
	- Dr. (`dr.` annotated as O)
	- 38 (`38` annotated as O)
	- 19 (`19` annotated as O)
	- 73 (`73` annotated as O)
	- 70 (`70` annotated as O)
	- Cyprus ( Greek ) (`cyprus greek` annotated as O)
	- 53 (`53` annotated as O)
	- Greenlander (`greenlander` annotated as O)
	- 55 (`55` annotated as O)
	- 77 (`77` annotated as O)
	- 43 (`43` annotated as O)
	- 72 (`72` annotated as O)
	- 62 (`62` annotated as O)
	- 76 (`76` annotated as O)

[('ms.', 10),
 ('dr.', 8),
 ('38', 7),
 ('19', 7),
 ('73', 6),
 ('70', 6),
 ('cyprus greek', 5),
 ('53', 5),
 ('greenlander', 5),
 ('55', 4),
 ('77', 4),
 ('43', 4),
 ('72', 4),
 ('62', 4),
 ('76', 4)]

#### More FN analysis

In [37]:
fns_df = ModelError.get_fns_dataframe(results.model_errors)

In [38]:
fns_df[["full_text", "token", "annotation", "prediction"]].head(20)

,full_text,token,annotation,prediction
0,42,42,O,AGE
1,OSLO,oslo,O,LOCATION
2,4253978024025234633,4253978024025234633,O,CREDIT_CARD
3,Bedřicha Smetany 405 Kutná Hora 1 Stipo Way,bedřicha smetany 405 kutná hora 1 stipo way,O,LOCATION
4,314 Αρτεμισίου 62 Apt . 601 ΛΕΜΕΣΟΣ LI 72513 Ibirapita 8057 Apt . 286 Dolores Uruguay,314 αρτεμισίου 62 601 λεμεσος li 72513 ibirapita 8057 286 dolores uruguay,O,LOCATION
5,73,73,O,AGE
6,Hofman,hofman,O,PERSON
7,AK Steel Holding Corporation\n,ak steel holding corporation\n,O,ORGANIZATION
8,489 Slovenčeva 107\n Suite 385\n Dutovlje\n Slovenia 08503,489 slovenčeva 107\n 385\n dutovlje\n slovenia 08503,O,LOCATION
9,9865 2117,9865 2117,O,PHONE_NUMBER
10,Schuepisstrasse 108 Cunha Pass,schuepisstrasse 108 cunha pass,O,LOCATION
11,0704 Rua das Hortências 1428,0704 rua das hortências 1428,O,LOCATION
12,Polish,polish,O,NRP
13,Roland Pena Roland,roland pena roland,O,PERSON
14,782459547569,782459547569,O,US_DRIVER_LICENSE
15,Affiano Ferrari\n\nPodgorje,affiano ferrari\n\npodgorje,O,PERSON
16,pri Slovenj Gradcu\nSlovenia,pri slovenj gradcu\nslovenia,O,LOCATION
17,Salumäe Estonia,salumäe estonia,O,LOCATION
18,Ms.,ms.,O,TITLE
19,Barese,barese,O,PERSON