## Evaluate Presidio Analyzer using the Presidio Evaluator framework

This notebook demonstrates how to evaluate a Presidio instance using the presidio-evaluator framework
Steps:
1. Load dataset from file
2. Simple dataset statistics
3. Define the AnalyzerEngine object (and its parameters)
4. Align the dataset's entities to Presidio's entities
5. Set up the Evaluator object
6. Run experiment
7. Evaluate results
8. Error analysis

For an example with a custom Presidio instance, see [notebook 5](5_Evaluate_Custom_Presidio_Analyzer.ipynb).

In [1]:
# install presidio evaluator via pip if not yet installed

#!pip install presidio-evaluator

In [2]:
from pathlib import Path
from pprint import pprint
from collections import Counter
from typing import Dict, List
import json

from presidio_evaluator import InputSample
from presidio_evaluator.evaluation import SpanEvaluator, ModelError, Plotter
from presidio_evaluator.experiment_tracking import get_experiment_tracker

import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

%reload_ext autoreload
%autoreload 2

/Users/jyu36/code/ic-llm/presidio/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:65: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/Users/jyu36/code/ic-llm/presidio/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

stanza and spacy_stanza are not installed
Flair is not installed by default

## 1. Load dataset from file

In [3]:
dataset_name = "synth_dataset_v2.json"
dataset = InputSample.read_dataset_json(Path(Path.cwd(), "data", dataset_name))
print(len(dataset))

tokenizing input:   0%|          | 0/1497 [00:00<?, ?it/s]

loading model en_core_web_sm

tokenizing input: 100%|██████████| 1497/1497 [00:06<00:00, 232.64it/s]

1497

This dataset was auto generated. See more info here [Synthetic data generation](1_Generate_data.ipynb).

In [4]:
def get_entity_counts(dataset: List[InputSample]) -> Dict:
    """Return a dictionary with counter per entity type."""
    entity_counter = Counter()
    for sample in dataset:
        for tag in sample.tags:
            entity_counter[tag] += 1
    return entity_counter

In [5]:
def get_entity_counts(dataset: List[InputSample]) -> Dict:
    """Return a dictionary with counter per entity type."""
    entity_counter = Counter()
    for sample in dataset:
        print("SAMPLE:", sample)
        for tag in sample.tags:
            print("TAG:", tag)
            entity_counter[tag] += 1
    return entity_counter

entity_counts = get_entity_counts(dataset)
print(entity_counts)
pprint(entity_counts.most_common(), compact=True)

SAMPLE: Full text: The Exversion Orchestra was founded in 1977. Since then, it has grown from a volunteer community orchestra to a fully professional orchestra serving Southern Tunisia
Spans: [Span(type: GPE, value: Tunisia, char_span: [158: 165]), Span(type: DATE_TIME, value: 1977, char_span: [39: 43]), Span(type: ORGANIZATION, value: Exversion, char_span: [4: 13])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: My name is Rubija
Spans: [Span(type: PERSON, value: Rubija, char_span: [11: 17])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: What is the limit for card 4454794511390933?
Spans: [Span(type: CREDIT_CARD, value: 4454794511390933, char_span: [27: 43])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
SAMPLE: Full text: When they weren't singing about Hobbits, satanic felines and interstellar journeys, they were singing about the verses from Faina D. Yefremova's Cautionary Tales. Is there a better example of unbridled creativity than early Yefremova?
Spans: [Span(type: PERSON, value: Yefremova, char_span: [224: 233]), Span(type: PERSON, value: Faina D. Yefremova, char_span: [124: 142])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
SAMPLE: Full text: Here's my SSN: 460-89-9847
Spans: [Span(type: US_SSN, value: 460-89-9847, char_span: [15: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
SAMPLE: Full text: Action & Adventure, Animation, Comedy, Kids & Family, Mystery & Suspense
Directed By:    Johannes Varvio
Spans: [Span(type: PERSON, value: Johannes Varvio, char_span: [89: 104])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: Bot: What's the name on the account? User: Šárka Ottová
Spans: [Span(type: PERSON, value: Šárka Ottová, char_span: [43: 55])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: Unlike the Christiansen novel, it's not about necrophilia. What it is about, I suppose is anyone's guess. A brilliant piece of baroque pop.
Spans: [Span(type: PERSON, value: Christiansen, char_span: [11: 23])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I will be travelling to Canada next week, so I need my passport to be ready by then
Spans: [Span(type: GPE, value: Canada, char_span: [24: 30])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: my driver's license number is 2270-66-1551
Spans: [Span(type: US_DRIVER_LICENSE, value: 2270-66-1551, char_span: [30: 42])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: This 79 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 79, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Billing address: Sara Schwarz
    28245 Puruntie 82 Apt. 595
   LAPPEENRANTA
    SK
    53650
Spans: [Span(type: ZIP_CODE, value: 53650, char_span: [88: 93]), Span(type: GPE, value: SK, char_span: [81: 83]), Span(type: GPE, value: LAPPEENRANTA, char_span: [64: 76]), Span(type: STREET_ADDRESS, value: Apt. 595, char_span: [52: 60]), Span(type: STREET_ADDRESS, value: Puruntie 82, char_span: [40: 51]), Span(type: STREET_ADDRESS, value: 28245, char_span: [34: 39]), Span(type: PERSON, value: Sara Schwarz, char_span: [17: 29])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
TAG: O
TAG: GPE
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: Ubul: What a wife.
Nicole: Remember me, Mary? When I killed your brother, I talked just like this!
John: You saved my life! How can I ever repay you?
Spans: [Span(type: PERSON, value: John, char_span: [99: 103]), Span(type: PERSON, value: Mary, char_span: [40: 44]), Span(type: PERSON, value: Nicole, char_span: [19: 25]), Span(type: PERSON, value: Ubul, char_span: [0: 4])]

TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Dr. Cettina Fanucci?
Spans: [Span(type: PERSON, value: Cettina Fanucci, char_span: [88: 103]), Span(type: TITLE, value: Dr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Dr. Berta Szöllössy?
Spans: [Span(type: PERSON, value: Berta Szöllössy, char_span: [88: 103]), Span(type: TITLE, value: Dr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: 3... 2... 1... liftoff!
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Unlike the Jensen novel, it's not about necrophilia. What it is about, I suppose is anyone's guess. A brilliant piece of baroque pop.
Spans: [Span(type: PERSON, value: Jensen, char_span: [11: 17])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: What's your last name? Magnusson
Spans: [Span(type: PERSON, value: Magnusson, char_span: [23: 32])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: My name is Siiri
Spans: [Span(type: PERSON, value: Siiri, char_span: [11: 16])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: William Hughes

20789 Allika 46
 Suite 501
 Riisa

 Estonia 62488
Spans: [Span(type: STREET_ADDRESS, value: 62488, char_span: [60: 65]), Span(type: GPE, value: Estonia, char_span: [52: 59]), Span(type: GPE, value: Riisa, char_span: [44: 49]), Span(type: STREET_ADDRESS, value: Suite 501, char_span: [33: 42]), Span(type: STREET_ADDRESS, value: Allika 46, char_span: [22: 31]), Span(type: STREET_ADDRESS, value: 20789, char_span: [16: 21]), Span(type: PERSON, value: William Hughes, char_span: [0: 14])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
TAG: O
TAG: GPE
TAG: STREET_ADDRESS
SAMPLE: Full text: Microbilt Corporation is the brainchild of our 3 founders: Kónya, Becker and Vasquez.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
Spans: [Span(type: PERSON, value: Vasquez, char_span: [77: 84]), Span(type: PERSON, value: Becker, char_span: [66: 72]), Span(type: PERSON, value: Kónya, char_span: [59: 64]), Span(type: ORGANIZATION, value: Microbilt Corporation, char_span: [0: 21])]

TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Tomomi Nishiyama lives at 86036 Rua do Arenque 1634, Goiânia
Spans: [Span(type: GPE, value: Goiânia, char_span: [53: 60]), Span(type: STREET_ADDRESS, value: Rua do Arenque 1634, char_span: [32: 51]), Span(type: STREET_ADDRESS, value: 86036, char_span: [26: 31]), Span(type: PERSON, value: Tomomi Nishiyama, char_span: [0: 16])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
SAMPLE: Full text: Verdafero is the brainchild of our 3 founders: Eklund, Michael and Hodge.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
Spans: [Span(type: PERSON, value: Hodge, char_span: [67: 72]), Span(type: PERSON, value: Michael, char_span: [55: 62]), Span(type: PERSON, value: Eklund, char_span: [47: 53]), Span(type: ORGANIZATION, value: Verdafero, char_span: [0: 9])]

TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: We moved here from Kenosha
Spans: [Span(type: GPE, value: Kenosha, char_span: [19: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: My website is http://www.ScrapbookInsider.com.pt/
Spans: [Span(type: DOMAIN_NAME, value: http://www.ScrapbookInsider.com.pt/, char_span: [14: 49])]

TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
SAMPLE: Full text: follow up with patricia desrosiers in a couple of months.
Spans: [Span(type: PERSON, value: patricia desrosiers, char_span: [15: 34])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: The Propublica office is at Růžena and Király u. 15.
Spans: [Span(type: STREET_ADDRESS, value: Růžena and Király u. 15., char_span: [28: 52]), Span(type: ORGANIZATION, value: Propublica, char_span: [4: 14])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: I've shared files with you https://ClickPhobia.com.br/
Spans: [Span(type: DOMAIN_NAME, value: https://ClickPhobia.com.br/, char_span: [27: 54])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
SAMPLE: Full text: My card 4131034282458809939 is expiring this month. Please let me know process to it's extend validity.
Spans: [Span(type: CREDIT_CARD, value: 4131034282458809939, char_span: [8: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Could you please send me the last billed amount for cc 4007070753690781 on my e-mail UtaKortig@jourrapide.com?
Spans: [Span(type: EMAIL_ADDRESS, value: UtaKortig@jourrapide.com, char_span: [85: 109]), Span(type: CREDIT_CARD, value: 4007070753690781, char_span: [55: 71])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
SAMPLE: Full text: The Avalara office is at PSC 0413, Box 8144
APO AA 42323
Spans: [Span(type: STREET_ADDRESS, value: PSC 0413, Box 8144
APO AA 42323, char_span: [25: 56]), Span(type: ORGANIZATION, value: Avalara, char_span: [4: 11])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: You said your email is UshurmaDratchev@rhyta.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: UshurmaDratchev@rhyta.com, char_span: [23: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I have done an online order but didn't get any message on my registered 905-674-3793. Could you please look into it ?
Spans: [Span(type: PHONE_NUMBER, value: 905-674-3793, char_span: [72: 84])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: This 74 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 74, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: card number 630427373398 is lost, can you please send a new one to 1987 74 Diakou Street
 Suite 680
 Kissousa
 Cyprus 36903? I am in ΛΕΥΚΩΣΙΑ for a business trip
Spans: [Span(type: GPE, value: ΛΕΥΚΩΣΙΑ, char_span: [133: 141]), Span(type: STREET_ADDRESS, value: 1987 74 Diakou Street
 Suite 680
 Kissousa
 Cyprus 36903, char_span: [67: 123]), Span(type: CREDIT_CARD, value: 630427373398, char_span: [12: 24])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: When: 2000-04-16 11:34:35
Where: UPTON SCUDAMORE Country Club.
Spans: [Span(type: GPE, value: UPTON SCUDAMORE, char_span: [33: 48]), Span(type: DATE_TIME, value: 2000-04-16 11:34:35, char_span: [6: 25])]

TAG: O
TAG: O
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm Naomi Ryan, originally from ΕΓΚΩΜΗ, and i'm 31 y/o.
Spans: [Span(type: AGE, value: 31, char_span: [48: 50]), Span(type: GPE, value: ΕΓΚΩΜΗ, char_span: [32: 38]), Span(type: PERSON, value: Naomi Ryan, char_span: [4: 14])]

TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm moving out of the country, so please cancel my subscription
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: It may be too that Kaczmarek was influenced by an earlier song, "Carry Me Back To Canada," which was arranged and sung by Bonifacy Kaczmarek in 1977 (though Meza's song was actually about a boat!).
Spans: [Span(type: PERSON, value: Meza, char_span: [157: 161]), Span(type: DATE_TIME, value: 1977, char_span: [144: 148]), Span(type: PERSON, value: Bonifacy Kaczmarek, char_span: [122: 140]), Span(type: GPE, value: Canada, char_span: [82: 88]), Span(type: PERSON, value: Kaczmarek, char_span: [19: 28])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: C'mon, sing it with me: "You picked a fine time to leave me Mette, four hungry children and a crop in the field..."
Spans: [Span(type: PERSON, value: Mette, char_span: [60: 65])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Why is Katrine so impulsive?
Spans: [Span(type: PERSON, value: Katrine, char_span: [7: 14])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Maybe it's under Mathias Ruud
Spans: [Span(type: PERSON, value: Mathias Ruud, char_span: [17: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: My credit card 6586108984332171 has been lost, Can I request you to block it.
Spans: [Span(type: CREDIT_CARD, value: 6586108984332171, char_span: [15: 31])]

TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Have you been to a Ravil G Yefimov concert before?
Spans: [Span(type: PERSON, value: Ravil G Yefimov, char_span: [19: 34])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: ZIP: 3520
Spans: [Span(type: ZIP_CODE, value: 3520, char_span: [5: 9])]

TAG: O
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: Estonia was super fun to visit!
Spans: [Span(type: GPE, value: Estonia, char_span: [0: 7])]

TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Janka M. Szász

Network and computer systems administrator

Personal Info:
Phone:
60-56-85-91

E-mail:
SzaszJanka@cuvox.de

Website:
https://www.UEarly.se/

Address:
Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173.
Spans: [Span(type: STREET_ADDRESS, value: Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173, char_span: [166: 239]), Span(type: DOMAIN_NAME, value: https://www.UEarly.se/, char_span: [133: 155]), Span(type: EMAIL_ADDRESS, value: SzaszJanka@cuvox.de, char_span: [103: 122]), Span(type: PHONE_NUMBER, value: 60-56-85-91, char_span: [82: 93]), Span(type: TITLE, value: Network and computer systems administrator, char_span: [16: 58]), Span(type: PERSON, value: Janka M. Szász, char_span: [0: 14])]

TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
SAMPLE: Full text: Bryan Maclean's killers sentenced to life in prison
Spans: [Span(type: PERSON, value: Bryan Maclean, char_span: [0: 13])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Jožef Albin had given Jožef Albin his address: 450 Præstevænget 15, København V
Spans: [Span(type: GPE, value: København V, char_span: [68: 79]), Span(type: STREET_ADDRESS, value: Præstevænget 15, char_span: [51: 66]), Span(type: STREET_ADDRESS, value: 450, char_span: [47: 50]), Span(type: PERSON, value: Jožef Albin, char_span: [22: 33]), Span(type: PERSON, value: Jožef Albin, char_span: [0: 11])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
TAG: GPE
SAMPLE: Full text: card number 347415977307943 is lost, can you please send a new one to 14 Crown Street Kishiev Squares
 Suite 321
 LONDON
 United Kingdom 75419? I am in Sutri for a business trip
Spans: [Span(type: GPE, value: Sutri, char_span: [152: 157]), Span(type: STREET_ADDRESS, value: 14 Crown Street Kishiev Squares
 Suite 321
 LONDON
 United Kingdom 75419, char_span: [70: 142]), Span(type: CREDIT_CARD, value: 347415977307943, char_span: [12: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O

## 2. Simple dataset statistics

In [6]:
entity_counts = get_entity_counts(dataset)
print("Count per entity:")
pprint(entity_counts.most_common(), compact=True)

print("\nMin and max number of tokens in dataset: "\
f"Min: {min([len(sample.tokens) for sample in dataset])}, "\
f"Max: {max([len(sample.tokens) for sample in dataset])}")

print(f"Min and max sentence length in dataset: " \
f"Min: {min([len(sample.full_text) for sample in dataset])}, "\
f"Max: {max([len(sample.full_text) for sample in dataset])}")

print("\nExample InputSample:")
print(dataset[0])

SAMPLE: Full text: The Exversion Orchestra was founded in 1977. Since then, it has grown from a volunteer community orchestra to a fully professional orchestra serving Southern Tunisia
Spans: [Span(type: GPE, value: Tunisia, char_span: [158: 165]), Span(type: DATE_TIME, value: 1977, char_span: [39: 43]), Span(type: ORGANIZATION, value: Exversion, char_span: [4: 13])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: My name is Rubija
Spans: [Span(type: PERSON, value: Rubija, char_span: [11: 17])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: What is the limit for card 4454794511390933?
Spans: [Span(type: CREDIT_CARD, value: 4454794511390933, char_span: [27: 43])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
SAMPLE: Full text: When they weren't singing about Hobbits, satanic felines and interstellar journeys, they were singing about the verses from Faina D. Yefremova's Cautionary Tales. Is there a better example of unbridled creativity than early Yefremova?
Spans: [Span(type: PERSON, value: Yefremova, char_span: [224: 233]), Span(type: PERSON, value: Faina D. Yefremova, char_span: [124: 142])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
SAMPLE: Full text: Here's my SSN: 460-89-9847
Spans: [Span(type: US_SSN, value: 460-89-9847, char_span: [15: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
SAMPLE: Full text: Action & Adventure, Animation, Comedy, Kids & Family, Mystery & Suspense
Directed By:    Johannes Varvio
Spans: [Span(type: PERSON, value: Johannes Varvio, char_span: [89: 104])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: Bot: What's the name on the account? User: Šárka Ottová
Spans: [Span(type: PERSON, value: Šárka Ottová, char_span: [43: 55])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: Unlike the Christiansen novel, it's not about necrophilia. What it is about, I suppose is anyone's guess. A brilliant piece of baroque pop.
Spans: [Span(type: PERSON, value: Christiansen, char_span: [11: 23])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I will be travelling to Canada next week, so I need my passport to be ready by then
Spans: [Span(type: GPE, value: Canada, char_span: [24: 30])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: my driver's license number is 2270-66-1551
Spans: [Span(type: US_DRIVER_LICENSE, value: 2270-66-1551, char_span: [30: 42])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: This 79 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 79, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Billing address: Sara Schwarz
    28245 Puruntie 82 Apt. 595
   LAPPEENRANTA
    SK
    53650
Spans: [Span(type: ZIP_CODE, value: 53650, char_span: [88: 93]), Span(type: GPE, value: SK, char_span: [81: 83]), Span(type: GPE, value: LAPPEENRANTA, char_span: [64: 76]), Span(type: STREET_ADDRESS, value: Apt. 595, char_span: [52: 60]), Span(type: STREET_ADDRESS, value: Puruntie 82, char_span: [40: 51]), Span(type: STREET_ADDRESS, value: 28245, char_span: [34: 39]), Span(type: PERSON, value: Sara Schwarz, char_span: [17: 29])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
TAG: O
TAG: GPE
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: Ubul: What a wife.
Nicole: Remember me, Mary? When I killed your brother, I talked just like this!
John: You saved my life! How can I ever repay you?
Spans: [Span(type: PERSON, value: John, char_span: [99: 103]), Span(type: PERSON, value: Mary, char_span: [40: 44]), Span(type: PERSON, value: Nicole, char_span: [19: 25]), Span(type: PERSON, value: Ubul, char_span: [0: 4])]

TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Dr. Cettina Fanucci?
Spans: [Span(type: PERSON, value: Cettina Fanucci, char_span: [88: 103]), Span(type: TITLE, value: Dr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Dr. Berta Szöllössy?
Spans: [Span(type: PERSON, value: Berta Szöllössy, char_span: [88: 103]), Span(type: TITLE, value: Dr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: 3... 2... 1... liftoff!
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Unlike the Jensen novel, it's not about necrophilia. What it is about, I suppose is anyone's guess. A brilliant piece of baroque pop.
Spans: [Span(type: PERSON, value: Jensen, char_span: [11: 17])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: What's your last name? Magnusson
Spans: [Span(type: PERSON, value: Magnusson, char_span: [23: 32])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: My name is Siiri
Spans: [Span(type: PERSON, value: Siiri, char_span: [11: 16])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: William Hughes

20789 Allika 46
 Suite 501
 Riisa

 Estonia 62488
Spans: [Span(type: STREET_ADDRESS, value: 62488, char_span: [60: 65]), Span(type: GPE, value: Estonia, char_span: [52: 59]), Span(type: GPE, value: Riisa, char_span: [44: 49]), Span(type: STREET_ADDRESS, value: Suite 501, char_span: [33: 42]), Span(type: STREET_ADDRESS, value: Allika 46, char_span: [22: 31]), Span(type: STREET_ADDRESS, value: 20789, char_span: [16: 21]), Span(type: PERSON, value: William Hughes, char_span: [0: 14])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
TAG: O
TAG: GPE
TAG: STREET_ADDRESS
SAMPLE: Full text: Microbilt Corporation is the brainchild of our 3 founders: Kónya, Becker and Vasquez.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
Spans: [Span(type: PERSON, value: Vasquez, char_span: [77: 84]), Span(type: PERSON, value: Becker, char_span: [66: 72]), Span(type: PERSON, value: Kónya, char_span: [59: 64]), Span(type: ORGANIZATION, value: Microbilt Corporation, char_span: [0: 21])]

TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Tomomi Nishiyama lives at 86036 Rua do Arenque 1634, Goiânia
Spans: [Span(type: GPE, value: Goiânia, char_span: [53: 60]), Span(type: STREET_ADDRESS, value: Rua do Arenque 1634, char_span: [32: 51]), Span(type: STREET_ADDRESS, value: 86036, char_span: [26: 31]), Span(type: PERSON, value: Tomomi Nishiyama, char_span: [0: 16])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
SAMPLE: Full text: Verdafero is the brainchild of our 3 founders: Eklund, Michael and Hodge.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
Spans: [Span(type: PERSON, value: Hodge, char_span: [67: 72]), Span(type: PERSON, value: Michael, char_span: [55: 62]), Span(type: PERSON, value: Eklund, char_span: [47: 53]), Span(type: ORGANIZATION, value: Verdafero, char_span: [0: 9])]

TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: We moved here from Kenosha
Spans: [Span(type: GPE, value: Kenosha, char_span: [19: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
SAMPLE: Full text: My website is http://www.ScrapbookInsider.com.pt/
Spans: [Span(type: DOMAIN_NAME, value: http://www.ScrapbookInsider.com.pt/, char_span: [14: 49])]

TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
SAMPLE: Full text: follow up with patricia desrosiers in a couple of months.
Spans: [Span(type: PERSON, value: patricia desrosiers, char_span: [15: 34])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: The Propublica office is at Růžena and Király u. 15.
Spans: [Span(type: STREET_ADDRESS, value: Růžena and Király u. 15., char_span: [28: 52]), Span(type: ORGANIZATION, value: Propublica, char_span: [4: 14])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: I've shared files with you https://ClickPhobia.com.br/
Spans: [Span(type: DOMAIN_NAME, value: https://ClickPhobia.com.br/, char_span: [27: 54])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
SAMPLE: Full text: My card 4131034282458809939 is expiring this month. Please let me know process to it's extend validity.
Spans: [Span(type: CREDIT_CARD, value: 4131034282458809939, char_span: [8: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Could you please send me the last billed amount for cc 4007070753690781 on my e-mail UtaKortig@jourrapide.com?
Spans: [Span(type: EMAIL_ADDRESS, value: UtaKortig@jourrapide.com, char_span: [85: 109]), Span(type: CREDIT_CARD, value: 4007070753690781, char_span: [55: 71])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
SAMPLE: Full text: The Avalara office is at PSC 0413, Box 8144
APO AA 42323
Spans: [Span(type: STREET_ADDRESS, value: PSC 0413, Box 8144
APO AA 42323, char_span: [25: 56]), Span(type: ORGANIZATION, value: Avalara, char_span: [4: 11])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
SAMPLE: Full text: You said your email is UshurmaDratchev@rhyta.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: UshurmaDratchev@rhyta.com, char_span: [23: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I have done an online order but didn't get any message on my registered 905-674-3793. Could you please look into it ?
Spans: [Span(type: PHONE_NUMBER, value: 905-674-3793, char_span: [72: 84])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: This 74 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 74, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: card number 630427373398 is lost, can you please send a new one to 1987 74 Diakou Street
 Suite 680
 Kissousa
 Cyprus 36903? I am in ΛΕΥΚΩΣΙΑ for a business trip
Spans: [Span(type: GPE, value: ΛΕΥΚΩΣΙΑ, char_span: [133: 141]), Span(type: STREET_ADDRESS, value: 1987 74 Diakou Street
 Suite 680
 Kissousa
 Cyprus 36903, char_span: [67: 123]), Span(type: CREDIT_CARD, value: 630427373398, char_span: [12: 24])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: When: 2000-04-16 11:34:35
Where: UPTON SCUDAMORE Country Club.
Spans: [Span(type: GPE, value: UPTON SCUDAMORE, char_span: [33: 48]), Span(type: DATE_TIME, value: 2000-04-16 11:34:35, char_span: [6: 25])]

TAG: O
TAG: O
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: GPE
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm Naomi Ryan, originally from ΕΓΚΩΜΗ, and i'm 31 y/o.
Spans: [Span(type: AGE, value: 31, char_span: [48: 50]), Span(type: GPE, value: ΕΓΚΩΜΗ, char_span: [32: 38]), Span(type: PERSON, value: Naomi Ryan, char_span: [4: 14])]

TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm moving out of the country, so please cancel my subscription
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: It may be too that Kaczmarek was influenced by an earlier song, "Carry Me Back To Canada," which was arranged and sung by Bonifacy Kaczmarek in 1977 (though Meza's song was actually about a boat!).
Spans: [Span(type: PERSON, value: Meza, char_span: [157: 161]), Span(type: DATE_TIME, value: 1977, char_span: [144: 148]), Span(type: PERSON, value: Bonifacy Kaczmarek, char_span: [122: 140]), Span(type: GPE, value: Canada, char_span: [82: 88]), Span(type: PERSON, value: Kaczmarek, char_span: [19: 28])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: C'mon, sing it with me: "You picked a fine time to leave me Mette, four hungry children and a crop in the field..."
Spans: [Span(type: PERSON, value: Mette, char_span: [60: 65])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Why is Katrine so impulsive?
Spans: [Span(type: PERSON, value: Katrine, char_span: [7: 14])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Maybe it's under Mathias Ruud
Spans: [Span(type: PERSON, value: Mathias Ruud, char_span: [17: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: My credit card 6586108984332171 has been lost, Can I request you to block it.
Spans: [Span(type: CREDIT_CARD, value: 6586108984332171, char_span: [15: 31])]

TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Have you been to a Ravil G Yefimov concert before?
Spans: [Span(type: PERSON, value: Ravil G Yefimov, char_span: [19: 34])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: ZIP: 3520
Spans: [Span(type: ZIP_CODE, value: 3520, char_span: [5: 9])]

TAG: O
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: Estonia was super fun to visit!
Spans: [Span(type: GPE, value: Estonia, char_span: [0: 7])]

TAG: GPE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Janka M. Szász

Network and computer systems administrator

Personal Info:
Phone:
60-56-85-91

E-mail:
SzaszJanka@cuvox.de

Website:
https://www.UEarly.se/

Address:
Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173.
Spans: [Span(type: STREET_ADDRESS, value: Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173, char_span: [166: 239]), Span(type: DOMAIN_NAME, value: https://www.UEarly.se/, char_span: [133: 155]), Span(type: EMAIL_ADDRESS, value: SzaszJanka@cuvox.de, char_span: [103: 122]), Span(type: PHONE_NUMBER, value: 60-56-85-91, char_span: [82: 93]), Span(type: TITLE, value: Network and computer systems administrator, char_span: [16: 58]), Span(type: PERSON, value: Janka M. Szász, char_span: [0: 14])]

TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DOMAIN_NAME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
SAMPLE: Full text: Bryan Maclean's killers sentenced to life in prison
Spans: [Span(type: PERSON, value: Bryan Maclean, char_span: [0: 13])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Jožef Albin had given Jožef Albin his address: 450 Præstevænget 15, København V
Spans: [Span(type: GPE, value: København V, char_span: [68: 79]), Span(type: STREET_ADDRESS, value: Præstevænget 15, char_span: [51: 66]), Span(type: STREET_ADDRESS, value: 450, char_span: [47: 50]), Span(type: PERSON, value: Jožef Albin, char_span: [22: 33]), Span(type: PERSON, value: Jožef Albin, char_span: [0: 11])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: STREET_ADDRESS
TAG: O
TAG: GPE
TAG: GPE
SAMPLE: Full text: card number 347415977307943 is lost, can you please send a new one to 14 Crown Street Kishiev Squares
 Suite 321
 LONDON
 United Kingdom 75419? I am in Sutri for a business trip
Spans: [Span(type: GPE, value: Sutri, char_span: [152: 157]), Span(type: STREET_ADDRESS, value: 14 Crown Street Kishiev Squares
 Suite 321
 LONDON
 United Kingdom 75419, char_span: [70: 142]), Span(type: CREDIT_CARD, value: 347415977307943, char_span: [12: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O

In [7]:
print("A few examples sentences containing each entity:\n")
for entity in entity_counts.keys():
    samples = [sample for sample in dataset if entity in set(sample.tags)]
    if len(samples) > 1 and entity != "O":
        print(f"Entity: <{entity}> two example sentences:\n"
              f"\n1) {samples[0].full_text}"
              f"\n2) {samples[1].full_text}"
              f"\n------------------------------------\n")

A few examples sentences containing each entity:

Entity: <ORGANIZATION> two example sentences:

1) The Exversion Orchestra was founded in 1977. Since then, it has grown from a volunteer community orchestra to a fully professional orchestra serving Southern Tunisia
2) Microbilt Corporation is the brainchild of our 3 founders: Kónya, Becker and Vasquez.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
------------------------------------

Entity: <DATE_TIME> two example sentences:

1) The Exversion Orchestra was founded in 1977. Since then, it has grown from a volunteer community orchestra to a fully professional orchestra serving Southern Tunisia
2) When: 2000-04-16 11:34:35
Where: UPTON SCUDAMORE Country Club.
------------------------------------

Entity: <GPE> two example sentences:

1) The Exversion Orchestra was founded in 1977. Since then, it has grown from a volunteer community orchestra to a fully professional orchestra serving Southern Tunisia
2) I will be travelling to Canada next week, so I need my passport to be ready by then
------------------------------------

Entity: <PERSON> two example sentences:

1) My name is Rubija
2) When they weren't singing about Hobbits, satanic felines and interstellar journeys, they were singing about the verses from Faina D. Yefremova's Cautionary Tales. Is there a better example of unbridled creativity than early Yefremova?
------------------------------------

Entity: <CREDIT_CARD> two example sentences:

1) What is the limit for card 4454794511390933?
2) My card 4131034282458809939 is expiring this month. Please let me know process to it's extend validity.
------------------------------------

Entity: <US_SSN> two example sentences:

1) Here's my SSN: 460-89-9847
2) Here's my SSN: 514-69-0360
------------------------------------

Entity: <US_DRIVER_LICENSE> two example sentences:

1) my driver's license number is 2270-66-1551
2) My driver's license number is 6940579
------------------------------------

Entity: <AGE> two example sentences:

1) This 79 year old female complaining of stomach pain.
2) This 74 year old female complaining of stomach pain.
------------------------------------

Entity: <STREET_ADDRESS> two example sentences:

1) Billing address: Sara Schwarz
    28245 Puruntie 82 Apt. 595
   LAPPEENRANTA
    SK
    53650
2) William Hughes

20789 Allika 46
 Suite 501
 Riisa

 Estonia 62488
------------------------------------

Entity: <ZIP_CODE> two example sentences:

1) Billing address: Sara Schwarz
    28245 Puruntie 82 Apt. 595
   LAPPEENRANTA
    SK
    53650
2) ZIP: 3520
------------------------------------

Entity: <TITLE> two example sentences:

1) My name appears incorrectly on credit card statement could you please correct it to Dr. Cettina Fanucci?
2) My name appears incorrectly on credit card statement could you please correct it to Dr. Berta Szöllössy?
------------------------------------

Entity: <DOMAIN_NAME> two example sentences:

1) My website is http://www.ScrapbookInsider.com.pt/
2) I've shared files with you https://ClickPhobia.com.br/
------------------------------------

Entity: <EMAIL_ADDRESS> two example sentences:

1) Could you please send me the last billed amount for cc 4007070753690781 on my e-mail UtaKortig@jourrapide.com?
2) You said your email is UshurmaDratchev@rhyta.com. Is that correct?
------------------------------------

Entity: <PHONE_NUMBER> two example sentences:

1) I have done an online order but didn't get any message on my registered 905-674-3793. Could you please look into it ?
2) Janka M. Szász

Network and computer systems administrator

Personal Info:
Phone:
60-56-85-91

E-mail:
SzaszJanka@cuvox.de

Website:
https://www.UEarly.se/

Address:
Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173.
------------------------------------

Entity: <IBAN_CODE> two example sentences:

1) Are there any charges applied for money transfer from GB56HXDO88167774656119 to other bank accounts
2) My IBAN is GB59IFUE40226315499137
------------------------------------

Entity: <IP_ADDRESS> two example sentences:

1) Inject SELECT * FROM Users WHERE client_ip = ?%//!%20\|106.31.73.20|%20/
2) Inject SELECT * FROM Users WHERE client_ip = ?%//!%20\|86.121.97.248|%20/
------------------------------------

Entity: <NRP> two example sentences:

1) From the film English graffiti (also features Kate M Begum. What's not to love?
2) The restaurant is located at 704 1436 Redbud Drive
Cite Essanaouber
, 32
 60810. It serves great Slovenian food.
------------------------------------

## 3. Define the AnalyzerEngine object 
Using Presidio with default parameters (not recommended, it's used here for simplicity). For an example on customization, see [notebook 5](5_Evaluate_Custom_Presidio_Analyzer.ipynb)

In [8]:
from presidio_analyzer import AnalyzerEngine
from presidio_analyzer.nlp_engine import NlpEngineProvider

# Loading the vanilla Analyzer Engine, with the default NER model.
configuration = {
    "nlp_engine_name": "spacy",
    "models": [{"lang_code": "en", "model_name": "en_core_web_sm"}],
}
provider = NlpEngineProvider(nlp_configuration=configuration)
nlp_engine_with_sm = provider.create_engine()
analyzer_engine = AnalyzerEngine(nlp_engine=nlp_engine_with_sm, default_score_threshold=0.4)

pprint(f"Supported entities for English:")
pprint(analyzer_engine.get_supported_entities("en"), compact=True)

print(f"\nLoaded recognizers for English:")
pprint([rec.name for rec in analyzer_engine.registry.get_recognizers("en", all_fields=True)], compact=True)

print(f"\nLoaded NER models:")
pprint(analyzer_engine.nlp_engine.models)

'Supported entities for English:'
['NRP', 'UK_NHS', 'AGE', 'US_BANK_NUMBER', 'CRYPTO', 'US_PASSPORT',
 'ORGANIZATION', 'URL', 'EMAIL', 'LOCATION', 'ID', 'MEDICAL_LICENSE',
 'IBAN_CODE', 'IP_ADDRESS', 'PHONE_NUMBER', 'PERSON', 'US_DRIVER_LICENSE',
 'DATE_TIME', 'CREDIT_CARD', 'MAC_ADDRESS', 'US_ITIN', 'US_SSN',
 'EMAIL_ADDRESS']

Loaded recognizers for English:
['CreditCardRecognizer', 'UsBankRecognizer', 'UsLicenseRecognizer',
 'UsItinRecognizer', 'UsPassportRecognizer', 'UsSsnRecognizer', 'NhsRecognizer',
 'CryptoRecognizer', 'DateRecognizer', 'EmailRecognizer', 'IbanRecognizer',
 'IpRecognizer', 'MedicalLicenseRecognizer', 'MacAddressRecognizer',
 'PhoneRecognizer', 'UrlRecognizer', 'SpacyRecognizer']

Loaded NER models:
[{'lang_code': 'en', 'model_name': 'en_core_web_sm'}]

## 4. Align the dataset's entities to Presidio's entities

There is possibly a difference between the names of entities in the dataset, and the names of entities Presidio can detect.
For example, it could be that a dataset labels a name as PER while Presidio returns PERSON. To be able to compare the predicted value to the actual and gather metrics, an alignment between the entity names is necessary. Consider changing the mapping if your dataset and/or Presidio instance supports difference entity types.

In [9]:
from presidio_evaluator.models import  PresidioAnalyzerWrapper

entities_mapping=PresidioAnalyzerWrapper.presidio_entities_map # default mapping

print("Using this mapping between the dataset and Presidio's entities:")
pprint(entities_mapping, compact=True)


dataset = SpanEvaluator.align_entity_types(
    dataset, 
    entities_mapping=entities_mapping, 
    allow_missing_mappings=True
)
new_entity_counts = get_entity_counts(dataset)
print("\nCount per entity after alignment:")
pprint(new_entity_counts.most_common(), compact=True)

dataset_entities = list(new_entity_counts.values())

Using this mapping between the dataset and Presidio's entities:
{'ADDRESS': 'LOCATION',
 'AGE': 'AGE',
 'BIRTHDAY': 'DATE_TIME',
 'CITY': 'LOCATION',
 'CREDIT_CARD': 'CREDIT_CARD',
 'CREDIT_CARD_NUMBER': 'CREDIT_CARD',
 'DATE': 'DATE_TIME',
 'DATE_OF_BIRTH': 'DATE_TIME',
 'DATE_TIME': 'DATE_TIME',
 'DOB': 'DATE_TIME',
 'DOMAIN': 'URL',
 'DOMAIN_NAME': 'URL',
 'EMAIL': 'EMAIL_ADDRESS',
 'EMAIL_ADDRESS': 'EMAIL_ADDRESS',
 'FACILITY': 'LOCATION',
 'FIRST_NAME': 'PERSON',
 'GPE': 'LOCATION',
 'HCW': 'PERSON',
 'HOSP': 'ORGANIZATION',
 'HOSPITAL': 'ORGANIZATION',
 'IBAN': 'IBAN_CODE',
 'IBAN_CODE': 'IBAN_CODE',
 'ID': 'ID',
 'IP_ADDRESS': 'IP_ADDRESS',
 'LAST_NAME': 'PERSON',
 'LOC': 'LOCATION',
 'LOCATION': 'LOCATION',
 'NAME': 'PERSON',
 'NATIONALITY': 'NRP',
 'NORP': 'NRP',
 'NRP': 'NRP',
 'O': 'O',
 'ORG': 'ORGANIZATION',
 'ORGANIZATION': 'ORGANIZATION',
 'PATIENT': 'PERSON',
 'PATORG': 'ORGANIZATION',
 'PER': 'PERSON',
 'PERSON': 'PERSON',
 'PHONE': 'PHONE_NUMBER',
 'PHONE_NUMBER': 'PHONE_NUMBER',
 'PREFIX': 'TITLE',
 'SSN': 'US_SSN',
 'STAFF': 'PERSON',
 'STREET_ADDRESS': 'LOCATION',
 'TIME': 'DATE_TIME',
 'TITLE': 'TITLE',
 'URL': 'URL',
 'US_DRIVER_LICENSE': 'US_DRIVER_LICENSE',
 'US_SSN': 'US_SSN',
 'VENDOR': 'ORGANIZATION',
 'ZIP': 'ZIP_CODE',
 'ZIP_CODE': 'ZIP_CODE'}
SAMPLE: Full text: The Exversion Orchestra was founded in 1977. Since then, it has grown from a volunteer community orchestra to a fully professional orchestra serving Southern Tunisia
Spans: [Span(type: LOCATION, value: Tunisia, char_span: [158: 165]), Span(type: DATE_TIME, value: 1977, char_span: [39: 43]), Span(type: ORGANIZATION, value: Exversion, char_span: [4: 13])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
SAMPLE: Full text: My name is Rubija
Spans: [Span(type: PERSON, value: Rubija, char_span: [11: 17])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: What is the limit for card 4454794511390933?
Spans: [Span(type: CREDIT_CARD, value: 4454794511390933, char_span: [27: 43])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
SAMPLE: Full text: When they weren't singing about Hobbits, satanic felines and interstellar journeys, they were singing about the verses from Faina D. Yefremova's Cautionary Tales. Is there a better example of unbridled creativity than early Yefremova?
Spans: [Span(type: PERSON, value: Yefremova, char_span: [224: 233]), Span(type: PERSON, value: Faina D. Yefremova, char_span: [124: 142])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
SAMPLE: Full text: Here's my SSN: 460-89-9847
Spans: [Span(type: US_SSN, value: 460-89-9847, char_span: [15: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
TAG: US_SSN
SAMPLE: Full text: Action & Adventure, Animation, Comedy, Kids & Family, Mystery & Suspense
Directed By:    Johannes Varvio
Spans: [Span(type: PERSON, value: Johannes Varvio, char_span: [89: 104])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: Bot: What's the name on the account? User: Šárka Ottová
Spans: [Span(type: PERSON, value: Šárka Ottová, char_span: [43: 55])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: Unlike the Christiansen novel, it's not about necrophilia. What it is about, I suppose is anyone's guess. A brilliant piece of baroque pop.
Spans: [Span(type: PERSON, value: Christiansen, char_span: [11: 23])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I will be travelling to Canada next week, so I need my passport to be ready by then
Spans: [Span(type: LOCATION, value: Canada, char_span: [24: 30])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: my driver's license number is 2270-66-1551
Spans: [Span(type: US_DRIVER_LICENSE, value: 2270-66-1551, char_span: [30: 42])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
TAG: US_DRIVER_LICENSE
SAMPLE: Full text: This 79 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 79, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Billing address: Sara Schwarz
    28245 Puruntie 82 Apt. 595
   LAPPEENRANTA
    SK
    53650
Spans: [Span(type: ZIP_CODE, value: 53650, char_span: [88: 93]), Span(type: LOCATION, value: SK, char_span: [81: 83]), Span(type: LOCATION, value: LAPPEENRANTA, char_span: [64: 76]), Span(type: LOCATION, value: Apt. 595, char_span: [52: 60]), Span(type: LOCATION, value: Puruntie 82, char_span: [40: 51]), Span(type: LOCATION, value: 28245, char_span: [34: 39]), Span(type: PERSON, value: Sara Schwarz, char_span: [17: 29])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: LOCATION
TAG: O
TAG: LOCATION
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: Ubul: What a wife.
Nicole: Remember me, Mary? When I killed your brother, I talked just like this!
John: You saved my life! How can I ever repay you?
Spans: [Span(type: PERSON, value: John, char_span: [99: 103]), Span(type: PERSON, value: Mary, char_span: [40: 44]), Span(type: PERSON, value: Nicole, char_span: [19: 25]), Span(type: PERSON, value: Ubul, char_span: [0: 4])]

TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Dr. Cettina Fanucci?
Spans: [Span(type: PERSON, value: Cettina Fanucci, char_span: [88: 103]), Span(type: TITLE, value: Dr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: My name appears incorrectly on credit card statement could you please correct it to Dr. Berta Szöllössy?
Spans: [Span(type: PERSON, value: Berta Szöllössy, char_span: [88: 103]), Span(type: TITLE, value: Dr., char_span: [84: 87])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: TITLE
TAG: PERSON
TAG: PERSON
TAG: O
SAMPLE: Full text: 3... 2... 1... liftoff!
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Unlike the Jensen novel, it's not about necrophilia. What it is about, I suppose is anyone's guess. A brilliant piece of baroque pop.
Spans: [Span(type: PERSON, value: Jensen, char_span: [11: 17])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: What's your last name? Magnusson
Spans: [Span(type: PERSON, value: Magnusson, char_span: [23: 32])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: My name is Siiri
Spans: [Span(type: PERSON, value: Siiri, char_span: [11: 16])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
SAMPLE: Full text: William Hughes

20789 Allika 46
 Suite 501
 Riisa

 Estonia 62488
Spans: [Span(type: LOCATION, value: 62488, char_span: [60: 65]), Span(type: LOCATION, value: Estonia, char_span: [52: 59]), Span(type: LOCATION, value: Riisa, char_span: [44: 49]), Span(type: LOCATION, value: Suite 501, char_span: [33: 42]), Span(type: LOCATION, value: Allika 46, char_span: [22: 31]), Span(type: LOCATION, value: 20789, char_span: [16: 21]), Span(type: PERSON, value: William Hughes, char_span: [0: 14])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: LOCATION
TAG: O
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: Microbilt Corporation is the brainchild of our 3 founders: Kónya, Becker and Vasquez.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
Spans: [Span(type: PERSON, value: Vasquez, char_span: [77: 84]), Span(type: PERSON, value: Becker, char_span: [66: 72]), Span(type: PERSON, value: Kónya, char_span: [59: 64]), Span(type: ORGANIZATION, value: Microbilt Corporation, char_span: [0: 21])]

TAG: ORGANIZATION
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Tomomi Nishiyama lives at 86036 Rua do Arenque 1634, Goiânia
Spans: [Span(type: LOCATION, value: Goiânia, char_span: [53: 60]), Span(type: LOCATION, value: Rua do Arenque 1634, char_span: [32: 51]), Span(type: LOCATION, value: 86036, char_span: [26: 31]), Span(type: PERSON, value: Tomomi Nishiyama, char_span: [0: 16])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: LOCATION
SAMPLE: Full text: Verdafero is the brainchild of our 3 founders: Eklund, Michael and Hodge.  The idea was born (on the beach) while they were constructing a website to be the basis of another start-up idea.
Spans: [Span(type: PERSON, value: Hodge, char_span: [67: 72]), Span(type: PERSON, value: Michael, char_span: [55: 62]), Span(type: PERSON, value: Eklund, char_span: [47: 53]), Span(type: ORGANIZATION, value: Verdafero, char_span: [0: 9])]

TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: We moved here from Kenosha
Spans: [Span(type: LOCATION, value: Kenosha, char_span: [19: 26])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
SAMPLE: Full text: My website is http://www.ScrapbookInsider.com.pt/
Spans: [Span(type: URL, value: http://www.ScrapbookInsider.com.pt/, char_span: [14: 49])]

TAG: O
TAG: O
TAG: O
TAG: URL
SAMPLE: Full text: follow up with patricia desrosiers in a couple of months.
Spans: [Span(type: PERSON, value: patricia desrosiers, char_span: [15: 34])]

TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: The Propublica office is at Růžena and Király u. 15.
Spans: [Span(type: LOCATION, value: Růžena and Király u. 15., char_span: [28: 52]), Span(type: ORGANIZATION, value: Propublica, char_span: [4: 14])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: I've shared files with you https://ClickPhobia.com.br/
Spans: [Span(type: URL, value: https://ClickPhobia.com.br/, char_span: [27: 54])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: URL
SAMPLE: Full text: My card 4131034282458809939 is expiring this month. Please let me know process to it's extend validity.
Spans: [Span(type: CREDIT_CARD, value: 4131034282458809939, char_span: [8: 27])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Could you please send me the last billed amount for cc 4007070753690781 on my e-mail UtaKortig@jourrapide.com?
Spans: [Span(type: EMAIL_ADDRESS, value: UtaKortig@jourrapide.com, char_span: [85: 109]), Span(type: CREDIT_CARD, value: 4007070753690781, char_span: [55: 71])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
SAMPLE: Full text: The Avalara office is at PSC 0413, Box 8144
APO AA 42323
Spans: [Span(type: LOCATION, value: PSC 0413, Box 8144
APO AA 42323, char_span: [25: 56]), Span(type: ORGANIZATION, value: Avalara, char_span: [4: 11])]

TAG: O
TAG: ORGANIZATION
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
SAMPLE: Full text: You said your email is UshurmaDratchev@rhyta.com. Is that correct?
Spans: [Span(type: EMAIL_ADDRESS, value: UshurmaDratchev@rhyta.com, char_span: [23: 48])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I have done an online order but didn't get any message on my registered 905-674-3793. Could you please look into it ?
Spans: [Span(type: PHONE_NUMBER, value: 905-674-3793, char_span: [72: 84])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: This 74 year old female complaining of stomach pain.
Spans: [Span(type: AGE, value: 74, char_span: [5: 7])]

TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: card number 630427373398 is lost, can you please send a new one to 1987 74 Diakou Street
 Suite 680
 Kissousa
 Cyprus 36903? I am in ΛΕΥΚΩΣΙΑ for a business trip
Spans: [Span(type: LOCATION, value: ΛΕΥΚΩΣΙΑ, char_span: [133: 141]), Span(type: LOCATION, value: 1987 74 Diakou Street
 Suite 680
 Kissousa
 Cyprus 36903, char_span: [67: 123]), Span(type: CREDIT_CARD, value: 630427373398, char_span: [12: 24])]

TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: When: 2000-04-16 11:34:35
Where: UPTON SCUDAMORE Country Club.
Spans: [Span(type: LOCATION, value: UPTON SCUDAMORE, char_span: [33: 48]), Span(type: DATE_TIME, value: 2000-04-16 11:34:35, char_span: [6: 25])]

TAG: O
TAG: O
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: DATE_TIME
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm Naomi Ryan, originally from ΕΓΚΩΜΗ, and i'm 31 y/o.
Spans: [Span(type: AGE, value: 31, char_span: [48: 50]), Span(type: LOCATION, value: ΕΓΚΩΜΗ, char_span: [32: 38]), Span(type: PERSON, value: Naomi Ryan, char_span: [4: 14])]

TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: AGE
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: I'm moving out of the country, so please cancel my subscription
Spans: []

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: It may be too that Kaczmarek was influenced by an earlier song, "Carry Me Back To Canada," which was arranged and sung by Bonifacy Kaczmarek in 1977 (though Meza's song was actually about a boat!).
Spans: [Span(type: PERSON, value: Meza, char_span: [157: 161]), Span(type: DATE_TIME, value: 1977, char_span: [144: 148]), Span(type: PERSON, value: Bonifacy Kaczmarek, char_span: [122: 140]), Span(type: LOCATION, value: Canada, char_span: [82: 88]), Span(type: PERSON, value: Kaczmarek, char_span: [19: 28])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: O
TAG: DATE_TIME
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: C'mon, sing it with me: "You picked a fine time to leave me Mette, four hungry children and a crop in the field..."
Spans: [Span(type: PERSON, value: Mette, char_span: [60: 65])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Why is Katrine so impulsive?
Spans: [Span(type: PERSON, value: Katrine, char_span: [7: 14])]

TAG: O
TAG: O
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Maybe it's under Mathias Ruud
Spans: [Span(type: PERSON, value: Mathias Ruud, char_span: [17: 29])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
SAMPLE: Full text: My credit card 6586108984332171 has been lost, Can I request you to block it.
Spans: [Span(type: CREDIT_CARD, value: 6586108984332171, char_span: [15: 31])]

TAG: O
TAG: O
TAG: O
TAG: CREDIT_CARD
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Have you been to a Ravil G Yefimov concert before?
Spans: [Span(type: PERSON, value: Ravil G Yefimov, char_span: [19: 34])]

TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: ZIP: 3520
Spans: [Span(type: ZIP_CODE, value: 3520, char_span: [5: 9])]

TAG: O
TAG: O
TAG: ZIP_CODE
SAMPLE: Full text: Estonia was super fun to visit!
Spans: [Span(type: LOCATION, value: Estonia, char_span: [0: 7])]

TAG: LOCATION
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Janka M. Szász

Network and computer systems administrator

Personal Info:
Phone:
60-56-85-91

E-mail:
SzaszJanka@cuvox.de

Website:
https://www.UEarly.se/

Address:
Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173.
Spans: [Span(type: LOCATION, value: Brucker Bundesstrasse 31 Zezig Streets
 Suite 245
 FÜRLING
 Austria 25173, char_span: [166: 239]), Span(type: URL, value: https://www.UEarly.se/, char_span: [133: 155]), Span(type: EMAIL_ADDRESS, value: SzaszJanka@cuvox.de, char_span: [103: 122]), Span(type: PHONE_NUMBER, value: 60-56-85-91, char_span: [82: 93]), Span(type: TITLE, value: Network and computer systems administrator, char_span: [16: 58]), Span(type: PERSON, value: Janka M. Szász, char_span: [0: 14])]

TAG: PERSON
TAG: PERSON
TAG: PERSON
TAG: O
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: TITLE
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: PHONE_NUMBER
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: EMAIL_ADDRESS
TAG: O
TAG: O
TAG: O
TAG: O
TAG: URL
TAG: O
TAG: O
TAG: O
TAG: O
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: LOCATION
TAG: O
SAMPLE: Full text: Bryan Maclean's killers sentenced to life in prison
Spans: [Span(type: PERSON, value: Bryan Maclean, char_span: [0: 13])]

TAG: PERSON
TAG: PERSON
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
TAG: O
SAMPLE: Full text: Jožef Albin had given Jožef Albin his address: 450 Præstevænget 15, København V

## 5. Set up the Evaluator object

In [10]:
# Set up the experiment tracker to log the experiment for reproducibility
experiment = get_experiment_tracker()

# Create the evaluator object
evaluator = SpanEvaluator(model=analyzer_engine)


# Track model and dataset params
params = {"dataset_name": dataset_name, 
          "model_name": evaluator.model.name}
params.update(evaluator.model.to_log())
experiment.log_parameters(params)
experiment.log_dataset_hash(dataset)
experiment.log_parameter("entity_mappings", json.dumps(entities_mapping))

--------
Entities supported by this Presidio Analyzer instance:
NRP, UK_NHS, AGE, US_BANK_NUMBER, CRYPTO, US_PASSPORT, ORGANIZATION, URL, EMAIL, LOCATION, ID, MEDICAL_LICENSE, IBAN_CODE, IP_ADDRESS, PHONE_NUMBER, PERSON, US_DRIVER_LICENSE, DATE_TIME, CREDIT_CARD, MAC_ADDRESS, US_ITIN, US_SSN, EMAIL_ADDRESS

/Users/jyu36/code/ic-llm/presidio/.venv/lib/python3.12/site-packages/presidio_evaluator/evaluation/base_evaluator.py:83: UserWarning: skip words not provided, using default skip words. If you want the evaluation to not use skip words, pass skip_words=[]
  warnings.warn("skip words not provided, using default skip words. "

## 6. Run experiment

In [11]:
%%time

## Run experiment

evaluation_results = evaluator.evaluate_all(dataset)
results = evaluator.calculate_score(evaluation_results)

# Track experiment results
experiment.log_metrics(results.to_log())
entities, confmatrix = results.to_confusion_matrix()
experiment.log_confusion_matrix(matrix=confmatrix, 
                                labels=entities)

# end experiment
experiment.end()

Running model PresidioAnalyzerWrapper on dataset...
Finished running model on dataset
saving experiment data to /Users/jyu36/code/ic-llm/presidio/experiment_20260320-214042.json
CPU times: user 9.08 s, sys: 114 ms, total: 9.2 s
Wall time: 9.37 s

## 7. Evaluate results

In [12]:
# Plot output
plotter = Plotter(results=results, 
                  model_name = evaluator.model.name, 
                  save_as="svg",
                  beta = 2) 

# Path of the directory to save the plots
output_folder = Path(Path.cwd(), "plotter_output")
plotter.plot_scores(output_folder=output_folder)

In [13]:
pprint({"PII F":results.pii_f, "PII recall": results.pii_recall, "PII precision": results.pii_precision})

{'PII F': 0.6532222709338009,
 'PII precision': 0.6903474903474903,
 'PII recall': 0.6445565969718817}

### 7a. False positives
#### Most common false positive tokens:

In [14]:
ModelError.most_common_fp_tokens(results.model_errors)

Most common false positive tokens:
[('iban', 15),
 ('comedy kids family mystery suspense', 13),
 ('ssn', 10),
 ('couple', 10),
 ('greek', 9),
 ('8', 9),
 ('salesperson', 9),
 ('sunday', 9),
 ('fuse tv', 8),
 ('60s', 8)]
---------------
Example sentence with each FP token:
	- IBAN (`iban` pred as ORGANIZATION)
	- Comedy , Kids & Family Mystery & Suspense (`comedy kids family mystery suspense` pred as ORGANIZATION)
	- SSN (`ssn` pred as ORGANIZATION)
	- a couple of months (`couple` pred as DATE_TIME)
	- Greek (`greek` pred as O)
	- 8 + years (`8` pred as DATE_TIME)
	- Salesperson (`salesperson` pred as PERSON)
	- the last Sunday (`sunday` pred as DATE_TIME)
	- Fuse TV (`fuse tv` pred as ORGANIZATION)
	- the 60s (`60s` pred as DATE_TIME)

[('iban', 15),
 ('comedy kids family mystery suspense', 13),
 ('ssn', 10),
 ('couple', 10),
 ('greek', 9),
 ('8', 9),
 ('salesperson', 9),
 ('sunday', 9),
 ('fuse tv', 8),
 ('60s', 8)]

#### More FP analysis

In [15]:
fps_df = ModelError.get_fps_dataframe(results.model_errors, entity=["PERSON"])
fps_df[["full_text", "token", "annotation", "prediction"]].head(20)

           full_text             token    annotation prediction
0        Salesperson       salesperson             O     PERSON
1         Discipline        discipline             O     PERSON
2          Orchestra         orchestra             O     PERSON
3         Discipline        discipline             O     PERSON
4        Salesperson       salesperson             O     PERSON
5        Salesperson       salesperson             O     PERSON
6         Discipline        discipline             O     PERSON
7        salesperson       salesperson             O     PERSON
8        Salesperson       salesperson             O     PERSON
9        Salesperson       salesperson             O     PERSON
10       Salesperson       salesperson             O     PERSON
11        Discipline        discipline             O     PERSON
12        Discipline        discipline             O     PERSON
13       Salesperson       salesperson             O     PERSON
14        Discipline        discipline             O     PERSON
15       Salesperson       salesperson             O     PERSON
16        Discipline        discipline             O     PERSON
17            Rubija            rubija  ORGANIZATION     PERSON
18             Siiri             siiri  ORGANIZATION     PERSON
19  Tomomi Nishiyama  tomomi nishiyama  ORGANIZATION     PERSON

### 7b. False negatives (FN)

#### Most common false negative examples + a few samples with FN

In [16]:
ModelError.most_common_fn_tokens(results.model_errors, n=15)

Most common false negative tokens:
[('greenlander', 11),
 ('dr.', 9),
 ('ms.', 9),
 ('46', 6),
 ('61', 6),
 ('64', 6),
 ('65', 6),
 ('54', 6),
 ('espoo', 6),
 ('21', 4),
 ('78', 4),
 ('wisława szczepańska', 4),
 ('47', 4),
 ('63', 4),
 ('58', 4)]
---------------
Example sentence with each FN token:
	- Greenlander (`greenlander` annotated as O)
	- Dr. (`dr.` annotated as O)
	- Ms. (`ms.` annotated as O)
	- 46 (`46` annotated as O)
	- 61 (`61` annotated as O)
	- 64 (`64` annotated as O)
	- 65 (`65` annotated as O)
	- 54 (`54` annotated as O)
	- ESPOO (`espoo` annotated as O)
	- 21 (`21` annotated as O)
	- 78 (`78` annotated as O)
	- Wisława Szczepańska (`wisława szczepańska` annotated as O)
	- 47 (`47` annotated as O)
	- 63 (`63` annotated as O)
	- 58 (`58` annotated as O)

[('greenlander', 11),
 ('dr.', 9),
 ('ms.', 9),
 ('46', 6),
 ('61', 6),
 ('64', 6),
 ('65', 6),
 ('54', 6),
 ('espoo', 6),
 ('21', 4),
 ('78', 4),
 ('wisława szczepańska', 4),
 ('47', 4),
 ('63', 4),
 ('58', 4)]

#### More FN analysis

In [17]:
fns_df = ModelError.get_fns_dataframe(results.model_errors)

In [18]:
fns_df[["full_text", "token", "annotation", "prediction"]].head(20)

,full_text,token,annotation,prediction
0,Exversion,exversion,O,ORGANIZATION
1,Tunisia,tunisia,O,LOCATION
2,Rubija,rubija,O,PERSON
3,Faina D. Yefremova Yefremova,faina d. yefremova yefremova,O,PERSON
4,Johannes Varvio,johannes varvio,O,PERSON
5,2270 - 66 - 1551,2270 66 1551,O,US_DRIVER_LICENSE
6,79,79,O,AGE
7,28245 Puruntie 82 Apt . 595 LAPPEENRANTA SK,28245 puruntie 82 595 lappeenranta sk,O,LOCATION
8,53650,53650,O,ZIP_CODE
9,Ubul Nicole Mary John,ubul nicole mary john,O,PERSON
10,Dr.,dr.,O,TITLE
11,Dr.,dr.,O,TITLE
12,Siiri,siiri,O,PERSON
13,20789 Allika 46 Suite 501 Riisa Estonia 62488,20789 allika 46 501 riisa estonia 62488,O,LOCATION
14,Kónya Becker Vasquez,kónya becker vasquez,O,PERSON
15,Tomomi Nishiyama,tomomi nishiyama,O,PERSON
16,86036 Rua do Arenque 1634 Goiânia,86036 rua arenque 1634 goiânia,O,LOCATION
17,Verdafero,verdafero,O,ORGANIZATION
18,Eklund Michael Hodge,eklund michael hodge,O,PERSON
19,patricia desrosiers,patricia desrosiers,O,PERSON